package it.govpay.servizi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-07-04T14:49:50.152+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.govpay.it/servizi/", name = "PagamentiTelematiciPA")
@XmlSeeAlso({it.govpay.servizi.pa.ObjectFactory.class, it.govpay.servizi.commons.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagamentiTelematiciPA {

    @WebMethod(action = "paVerificaVersamento")
    @WebResult(name = "paVerificaVersamentoResponse", targetNamespace = "http://www.govpay.it/servizi/pa/", partName = "bodyrisposta")
    public it.govpay.servizi.pa.PaVerificaVersamentoResponse paVerificaVersamento(
        @WebParam(partName = "bodyrichiesta", name = "paVerificaVersamento", targetNamespace = "http://www.govpay.it/servizi/pa/")
        it.govpay.servizi.pa.PaVerificaVersamento bodyrichiesta
    );

    @WebMethod(action = "paNotificaTransazione")
    @WebResult(name = "paNotificaTransazioneResponse", targetNamespace = "http://www.govpay.it/servizi/pa/", partName = "bodyrisposta")
    public java.lang.String paNotificaTransazione(
        @WebParam(partName = "bodyrichiesta", name = "paNotificaTransazione", targetNamespace = "http://www.govpay.it/servizi/pa/")
        it.govpay.servizi.pa.PaNotificaTransazione bodyrichiesta
    );

    @WebMethod(action = "paNotificaStorno")
    @WebResult(name = "paNotificaStornoResponse", targetNamespace = "http://www.govpay.it/servizi/pa/", partName = "bodyrisposta")
    public java.lang.String paNotificaStorno(
        @WebParam(partName = "bodyrichiesta", name = "paNotificaStorno", targetNamespace = "http://www.govpay.it/servizi/pa/")
        it.govpay.servizi.pa.PaNotificaStorno bodyrichiesta
    );
}
