version: '3.3'

services:

  govpay:
    image: govpay:latest
    ports:
      - 8080:8080
    links:
      - pggovpay:pggovpay
    depends_on:
      - pggovpay

  pggovpay:
    image: postgres:9.2
    environment:
      - POSTGRES_PASSWORD=govpaypw
      - POSTGRES_USER=govpay
      - POSTGRES_DB=govpay
      - SCHEMA=govpay
      - PG_WORK_MEM=64MB
      - PG_MAINTENANCE_WORK_MEM=512MB
    command: postgres -c max_connections=300 -c log_min_messages=LOG -c 'shared_buffers=512MB'
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./docker/initdb:/docker-entrypoint-initdb.d/
