//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package itZZ.gov.digitpa.schemas._2011.psp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctErogazione complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctErogazione">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoPeriodo" type="{}stTipoPeriodo" minOccurs="0"/>
 *         &lt;element name="giorno" type="{}stText35" minOccurs="0"/>
 *         &lt;element name="fasciaOraria" type="{}ctFasciaOraria" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctErogazione", propOrder = {
    "tipoPeriodo",
    "giorno",
    "fasciaOrarias"
})
public class CtErogazione {

    protected StTipoPeriodo tipoPeriodo;
    protected String giorno;
    @XmlElement(name = "fasciaOraria")
    protected List<CtFasciaOraria> fasciaOrarias;

    /**
     * Gets the value of the tipoPeriodo property.
     * 
     * @return
     *     possible object is
     *     {@link StTipoPeriodo }
     *     
     */
    public StTipoPeriodo getTipoPeriodo() {
        return this.tipoPeriodo;
    }

    /**
     * Sets the value of the tipoPeriodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StTipoPeriodo }
     *     
     */
    public void setTipoPeriodo(StTipoPeriodo value) {
        this.tipoPeriodo = value;
    }

    /**
     * Gets the value of the giorno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiorno() {
        return this.giorno;
    }

    /**
     * Sets the value of the giorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiorno(String value) {
        this.giorno = value;
    }

    /**
     * Gets the value of the fasciaOrarias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fasciaOrarias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFasciaOrarias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtFasciaOraria }
     * 
     * 
     */
    public List<CtFasciaOraria> getFasciaOrarias() {
        if (this.fasciaOrarias == null) {
            this.fasciaOrarias = new ArrayList<>();
        }
        return this.fasciaOrarias;
    }

}
