//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package itZZ.gov.digitpa.schemas._2011.psp;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import it.govpay.core.utils.adapter.DecimalAdapter;


/**
 * <p>Java class for ctFasciaCostoServizio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctFasciaCostoServizio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="importoMassimoFascia" type="{}stImporto"/>
 *         &lt;element name="costoFisso" type="{}stImporto"/>
 *         &lt;element name="valoreCommissione" type="{}stImporto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctFasciaCostoServizio", propOrder = {
    "importoMassimoFascia",
    "costoFisso",
    "valoreCommissione"
})
public class CtFasciaCostoServizio {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(DecimalAdapter.class)
    protected BigDecimal importoMassimoFascia;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(DecimalAdapter.class)
    protected BigDecimal costoFisso;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(DecimalAdapter.class)
    protected BigDecimal valoreCommissione;

    /**
     * Gets the value of the importoMassimoFascia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getImportoMassimoFascia() {
        return this.importoMassimoFascia;
    }

    /**
     * Sets the value of the importoMassimoFascia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportoMassimoFascia(BigDecimal value) {
        this.importoMassimoFascia = value;
    }

    /**
     * Gets the value of the costoFisso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getCostoFisso() {
        return this.costoFisso;
    }

    /**
     * Sets the value of the costoFisso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostoFisso(BigDecimal value) {
        this.costoFisso = value;
    }

    /**
     * Gets the value of the valoreCommissione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getValoreCommissione() {
        return this.valoreCommissione;
    }

    /**
     * Sets the value of the valoreCommissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValoreCommissione(BigDecimal value) {
        this.valoreCommissione = value;
    }

}
