//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package itZZ.gov.digitpa.schemas._2011.psp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctInformazioniServizio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctInformazioniServizio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codiceLingua" type="{}stCodiceLingua"/>
 *         &lt;element name="descrizioneServizio" type="{}stText140" minOccurs="0"/>
 *         &lt;element name="disponibilitaServizio" type="{}stText140"/>
 *         &lt;element name="limitazioniServizio" type="{}stText140" minOccurs="0"/>
 *         &lt;element name="urlInformazioniCanale" type="{}stUrlInformazioni" minOccurs="0"/>
 *         &lt;element name="condizioniEconomicheMassime" type="{}stText35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctInformazioniServizio", propOrder = {
    "codiceLingua",
    "descrizioneServizio",
    "disponibilitaServizio",
    "limitazioniServizio",
    "urlInformazioniCanale",
    "condizioniEconomicheMassime"
})
public class CtInformazioniServizio {

    @XmlElement(required = true)
    protected StCodiceLingua codiceLingua;
    protected String descrizioneServizio;
    @XmlElement(required = true)
    protected String disponibilitaServizio;
    protected String limitazioniServizio;
    protected String urlInformazioniCanale;
    protected String condizioniEconomicheMassime;

    /**
     * Gets the value of the codiceLingua property.
     * 
     * @return
     *     possible object is
     *     {@link StCodiceLingua }
     *     
     */
    public StCodiceLingua getCodiceLingua() {
        return this.codiceLingua;
    }

    /**
     * Sets the value of the codiceLingua property.
     * 
     * @param value
     *     allowed object is
     *     {@link StCodiceLingua }
     *     
     */
    public void setCodiceLingua(StCodiceLingua value) {
        this.codiceLingua = value;
    }

    /**
     * Gets the value of the descrizioneServizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizioneServizio() {
        return this.descrizioneServizio;
    }

    /**
     * Sets the value of the descrizioneServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizioneServizio(String value) {
        this.descrizioneServizio = value;
    }

    /**
     * Gets the value of the disponibilitaServizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisponibilitaServizio() {
        return this.disponibilitaServizio;
    }

    /**
     * Sets the value of the disponibilitaServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisponibilitaServizio(String value) {
        this.disponibilitaServizio = value;
    }

    /**
     * Gets the value of the limitazioniServizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimitazioniServizio() {
        return this.limitazioniServizio;
    }

    /**
     * Sets the value of the limitazioniServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimitazioniServizio(String value) {
        this.limitazioniServizio = value;
    }

    /**
     * Gets the value of the urlInformazioniCanale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlInformazioniCanale() {
        return this.urlInformazioniCanale;
    }

    /**
     * Sets the value of the urlInformazioniCanale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlInformazioniCanale(String value) {
        this.urlInformazioniCanale = value;
    }

    /**
     * Gets the value of the condizioniEconomicheMassime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondizioniEconomicheMassime() {
        return this.condizioniEconomicheMassime;
    }

    /**
     * Sets the value of the condizioniEconomicheMassime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondizioniEconomicheMassime(String value) {
        this.condizioniEconomicheMassime = value;
    }

}
