//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package itZZ.gov.digitpa.schemas._2011.psp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctListaFasceCostoServizio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctListaFasceCostoServizio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fasciaCostoServizio" type="{}ctFasciaCostoServizio" maxOccurs="8"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctListaFasceCostoServizio", propOrder = {
    "fasciaCostoServizios"
})
public class CtListaFasceCostoServizio {

    @XmlElement(name = "fasciaCostoServizio", required = true)
    protected List<CtFasciaCostoServizio> fasciaCostoServizios;

    /**
     * Gets the value of the fasciaCostoServizios property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fasciaCostoServizios property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFasciaCostoServizios().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtFasciaCostoServizio }
     * 
     * 
     */
    public List<CtFasciaCostoServizio> getFasciaCostoServizios() {
        if (this.fasciaCostoServizios == null) {
            this.fasciaCostoServizios = new ArrayList<>();
        }
        return this.fasciaCostoServizios;
    }

}
