//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package itZZ.gov.digitpa.schemas._2011.psp;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import it.govpay.core.utils.adapter.DateTimeAdapter;


/**
 * <p>Java class for ctInformativaControparte complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctInformativaControparte">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identificativoFlusso" type="{}stText35"/>
 *         &lt;element name="identificativoDominio" type="{}stText35"/>
 *         &lt;element name="ragioneSociale" type="{}stText70"/>
 *         &lt;element name="dataPubblicazione" type="{}stDateTimeGiornoOra"/>
 *         &lt;element name="dataInizioValidita" type="{}stDateTimeGiornoOra"/>
 *         &lt;element name="pagamentiPressoPSP" type="{}stPagamentiPressoPSP"/>
 *         &lt;element name="erogazioneServizio" type="{}ctErogazioneServizio"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctInformativaControparte", propOrder = {
    "identificativoFlusso",
    "identificativoDominio",
    "ragioneSociale",
    "dataPubblicazione",
    "dataInizioValidita",
    "pagamentiPressoPSP",
    "erogazioneServizio"
})
@XmlRootElement(name = "informativaControparte")
public class InformativaControparte {

    @XmlElement(required = true)
    protected String identificativoFlusso;
    @XmlElement(required = true)
    protected String identificativoDominio;
    @XmlElement(required = true)
    protected String ragioneSociale;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    protected Date dataPubblicazione;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    protected Date dataInizioValidita;
    protected int pagamentiPressoPSP;
    @XmlElement(required = true)
    protected CtErogazioneServizio erogazioneServizio;

    /**
     * Gets the value of the identificativoFlusso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativoFlusso() {
        return this.identificativoFlusso;
    }

    /**
     * Sets the value of the identificativoFlusso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativoFlusso(String value) {
        this.identificativoFlusso = value;
    }

    /**
     * Gets the value of the identificativoDominio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativoDominio() {
        return this.identificativoDominio;
    }

    /**
     * Sets the value of the identificativoDominio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativoDominio(String value) {
        this.identificativoDominio = value;
    }

    /**
     * Gets the value of the ragioneSociale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRagioneSociale() {
        return this.ragioneSociale;
    }

    /**
     * Sets the value of the ragioneSociale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRagioneSociale(String value) {
        this.ragioneSociale = value;
    }

    /**
     * Gets the value of the dataPubblicazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDataPubblicazione() {
        return this.dataPubblicazione;
    }

    /**
     * Sets the value of the dataPubblicazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPubblicazione(Date value) {
        this.dataPubblicazione = value;
    }

    /**
     * Gets the value of the dataInizioValidita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDataInizioValidita() {
        return this.dataInizioValidita;
    }

    /**
     * Sets the value of the dataInizioValidita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataInizioValidita(Date value) {
        this.dataInizioValidita = value;
    }

    /**
     * Gets the value of the pagamentiPressoPSP property.
     * 
     */
    public int getPagamentiPressoPSP() {
        return this.pagamentiPressoPSP;
    }

    /**
     * Sets the value of the pagamentiPressoPSP property.
     * 
     */
    public void setPagamentiPressoPSP(int value) {
        this.pagamentiPressoPSP = value;
    }

    /**
     * Gets the value of the erogazioneServizio property.
     * 
     * @return
     *     possible object is
     *     {@link CtErogazioneServizio }
     *     
     */
    public CtErogazioneServizio getErogazioneServizio() {
        return this.erogazioneServizio;
    }

    /**
     * Sets the value of the erogazioneServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtErogazioneServizio }
     *     
     */
    public void setErogazioneServizio(CtErogazioneServizio value) {
        this.erogazioneServizio = value;
    }

}
