//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package itZZ.gov.digitpa.schemas._2011.psp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stTipoPeriodo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stTipoPeriodo">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="giornaliera"/>
 *     &lt;enumeration value="settimanale"/>
 *     &lt;enumeration value="mensile"/>
 *     &lt;enumeration value="annuale"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stTipoPeriodo")
@XmlEnum
public enum StTipoPeriodo {

    @XmlEnumValue("giornaliera")
    GIORNALIERA("giornaliera"),
    @XmlEnumValue("settimanale")
    SETTIMANALE("settimanale"),
    @XmlEnumValue("mensile")
    MENSILE("mensile"),
    @XmlEnumValue("annuale")
    ANNUALE("annuale");
    private final String value;

    StTipoPeriodo(String v) {
        this.value = v;
    }

    public String value() {
        return this.value;
    }

    public static StTipoPeriodo fromValue(String v) {
        for (StTipoPeriodo c: StTipoPeriodo.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
