//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package it.gov.spcoop.avvisopagamentopa.informazioniversamentoqr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctNumeroAvviso complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctNumeroAvviso">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="auxDigit" type="{http://AvvisoPagamentoPA.spcoop.gov.it/InformazioniVersamentoQR}stAuxDigit"/>
 *         &lt;element name="applicationCode" type="{http://AvvisoPagamentoPA.spcoop.gov.it/InformazioniVersamentoQR}stApplicationCode"/>
 *         &lt;element name="IUV" type="{http://AvvisoPagamentoPA.spcoop.gov.it/InformazioniVersamentoQR}stIUV"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctNumeroAvviso", propOrder = {
    "auxDigit",
    "applicationCode",
    "iuv"
})
public class CtNumeroAvviso {

    @XmlElement(required = true)
    protected String auxDigit;
    @XmlElement(required = true)
    protected String applicationCode;
    @XmlElement(name = "IUV", required = true)
    protected String iuv;

    /**
     * Gets the value of the auxDigit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuxDigit() {
        return this.auxDigit;
    }

    /**
     * Sets the value of the auxDigit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuxDigit(String value) {
        this.auxDigit = value;
    }

    /**
     * Gets the value of the applicationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationCode() {
        return this.applicationCode;
    }

    /**
     * Sets the value of the applicationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationCode(String value) {
        this.applicationCode = value;
    }

    /**
     * Gets the value of the iuv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIUV() {
        return this.iuv;
    }

    /**
     * Sets the value of the iuv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIUV(String value) {
        this.iuv = value;
    }

}
