package it.gov.spcoop.nodopagamentispc.servizi.pagamentitelematicirt;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-07-04T14:49:49.791+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciRTservice", 
                  wsdlLocation = "classpath:wsdl/PaPerNodo.wsdl",
                  targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT") 
public class PagamentiTelematiciRTservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT", "PagamentiTelematiciRTservice");
    public final static QName PPTPort = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT", "PPTPort");
    static {
        URL url = PagamentiTelematiciRTservice.class.getClassLoader().getResource("wsdl/PaPerNodo.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciRTservice.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/PaPerNodo.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PagamentiTelematiciRTservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciRTservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciRTservice() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns PagamentiTelematiciRT
     */
    @WebEndpoint(name = "PPTPort")
    public PagamentiTelematiciRT getPPTPort() {
        return super.getPort(PPTPort, PagamentiTelematiciRT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciRT
     */
    @WebEndpoint(name = "PPTPort")
    public PagamentiTelematiciRT getPPTPort(WebServiceFeature... features) {
        return super.getPort(PPTPort, PagamentiTelematiciRT.class, features);
    }

}
