openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/govpay/backend/api/gde
  description: Generated server url
paths:
  /eventi:
    get:
      tags:
      - gde-controller
      operationId: findEventi
      parameters:
      - name: pageable
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      - name: dataDa
        in: query
        required: false
        schema:
          type: string
          format: date-time
      - name: dataA
        in: query
        required: false
        schema:
          type: string
          format: date-time
      - name: idDominio
        in: query
        required: false
        schema:
          type: string
      - name: iuv
        in: query
        required: false
        schema:
          type: string
      - name: ccp
        in: query
        required: false
        schema:
          type: string
      - name: idA2A
        in: query
        required: false
        schema:
          type: string
      - name: idPendenza
        in: query
        required: false
        schema:
          type: string
      - name: idPagamento
        in: query
        required: false
        schema:
          type: string
      - name: categoriaEvento
        in: query
        required: false
        schema:
          type: string
          enum:
          - INTERNO
          - INTERFACCIA
          - UTENTE
      - name: esitoEvento
        in: query
        required: false
        schema:
          type: string
          enum:
          - OK
          - KO
          - FAIL
      - name: ruoloEvento
        in: query
        required: false
        schema:
          type: string
          enum:
          - CLIENT
          - SERVER
      - name: sottotipoEvento
        in: query
        required: false
        schema:
          type: string
      - name: tipoEvento
        in: query
        required: false
        schema:
          type: string
      - name: componenteEvento
        in: query
        required: false
        schema:
          type: string
          enum:
          - API_BACKOFFICE
          - API_ENTE
          - API_PAGOPA
          - API_PAGAMENTO
          - API_PENDENZE
          - API_RAGIONERIA
          - API_BACKEND_IO
          - API_SECIM
          - API_MYPIVOT
          - API_MAGGIOLI_JPPA
          - API_GOVPAY
          - API_HYPERSIC_APK
          - API_USER
          - GOVPAY
      - name: severitaDa
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: severitaA
        in: query
        required: false
        schema:
          type: integer
          format: int32
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedModelEventoIndexModel'
    post:
      tags:
      - gde-controller
      operationId: addEvento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nuovoEvento'
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /eventi/{id}:
    get:
      tags:
      - gde-controller
      operationId: getEventoById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/evento'
components:
  schemas:
    problem:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
    Links:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Link'
    datiPagoPA:
      type: object
      properties:
        idPsp:
          type: string
        idCanale:
          type: string
        idIntermediarioPsp:
          type: string
        tipoVersamento:
          type: string
        modelloPagamento:
          type: string
        idDominio:
          type: string
        idIntermediario:
          type: string
        idStazione:
          type: string
        idRiconciliazione:
          type: string
        sct:
          type: string
        idFlusso:
          type: string
        dataFlusso:
          type: string
          format: date-time
        idTracciato:
          type: number
        _links:
          $ref: '#/components/schemas/Links'
    nuovoEvento:
      type: object
      properties:
        id:
          type: integer
          format: int64
        componente:
          type: string
          enum:
          - API_BACKOFFICE
          - API_ENTE
          - API_PAGOPA
          - API_PAGAMENTO
          - API_PENDENZE
          - API_RAGIONERIA
          - API_BACKEND_IO
          - API_SECIM
          - API_MYPIVOT
          - API_MAGGIOLI_JPPA
          - API_GOVPAY
          - API_HYPERSIC_APK
          - API_USER
          - GOVPAY
        categoriaEvento:
          type: string
          enum:
          - INTERNO
          - INTERFACCIA
          - UTENTE
        ruolo:
          type: string
          enum:
          - CLIENT
          - SERVER
        tipoEvento:
          type: string
        esito:
          type: string
          enum:
          - OK
          - KO
          - FAIL
        dataEvento:
          type: string
          format: date-time
        durataEvento:
          type: integer
          format: int64
        sottotipoEvento:
          type: string
        sottotipoEsito:
          type: string
        dettaglioEsito:
          type: string
        idDominio:
          type: string
        iuv:
          type: string
        ccp:
          type: string
        idA2A:
          type: string
        idPendenza:
          type: string
        idPagamento:
          type: string
        datiPagoPA:
          $ref: '#/components/schemas/datiPagoPA'
        severita:
          type: integer
          format: int32
        parametriRichiesta:
          type: object
        parametriRisposta:
          type: object
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    PagedModelEventoIndexModel:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            eventi:
              type: array
              items:
                $ref: '#/components/schemas/evento'
        _links:
          $ref: '#/components/schemas/Links'
        page:
          $ref: '#/components/schemas/PageMetadata'
    evento:
      type: object
      properties:
        id:
          type: integer
          format: int64
        componente:
          type: string
          enum:
          - API_BACKOFFICE
          - API_ENTE
          - API_PAGOPA
          - API_PAGAMENTO
          - API_PENDENZE
          - API_RAGIONERIA
          - API_BACKEND_IO
          - API_SECIM
          - API_MYPIVOT
          - API_MAGGIOLI_JPPA
          - API_GOVPAY
          - API_HYPERSIC_APK
          - API_USER
          - GOVPAY
        categoriaEvento:
          type: string
          enum:
          - INTERNO
          - INTERFACCIA
          - UTENTE
        ruolo:
          type: string
          enum:
          - CLIENT
          - SERVER
        tipoEvento:
          type: string
        esito:
          type: string
          enum:
          - OK
          - KO
          - FAIL
        dataEvento:
          type: string
          format: date-time
        durataEvento:
          type: integer
          format: int64
        sottotipoEvento:
          type: string
        sottotipoEsito:
          type: string
        dettaglioEsito:
          type: string
        idDominio:
          type: string
        iuv:
          type: string
        ccp:
          type: string
        idA2A:
          type: string
        idPendenza:
          type: string
        idPagamento:
          type: string
        datiPagoPA:
          $ref: '#/components/schemas/datiPagoPA'
        severita:
          type: integer
          format: int32
        _links:
          $ref: '#/components/schemas/Links'
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
