package it.govpay.servizi.v2_5;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-07-04T14:49:50.278+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.govpay.it/servizi/v2_5", name = "PagamentiTelematiciGPApp")
@XmlSeeAlso({it.govpay.servizi.v2_3.gpapp.ObjectFactory.class, it.govpay.servizi.commons.ObjectFactory.class, it.govpay.servizi.v2_3.commons.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagamentiTelematiciGPApp {

    @WebMethod(action = "gpChiediFlussoRendicontazione")
    @WebResult(name = "gpChiediFlussoRendicontazioneResponse", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/", partName = "bodyrisposta")
    public it.govpay.servizi.v2_3.gpapp.GpChiediFlussoRendicontazioneResponse gpChiediFlussoRendicontazione(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediFlussoRendicontazione", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/")
        it.govpay.servizi.v2_3.gpapp.GpChiediFlussoRendicontazione bodyrichiesta
    );

    @WebMethod(action = "gpNotificaPagamento")
    @WebResult(name = "gpNotificaPagamentoResponse", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/", partName = "bodyrisposta")
    public it.govpay.servizi.v2_3.commons.GpResponse gpNotificaPagamento(
        @WebParam(partName = "bodyrichiesta", name = "gpNotificaPagamento", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/")
        it.govpay.servizi.v2_3.gpapp.GpNotificaPagamento bodyrichiesta
    );

    @WebMethod(action = "gpCaricaIuv")
    @WebResult(name = "gpCaricaIuvResponse", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/", partName = "bodyrichiesta")
    public it.govpay.servizi.v2_3.gpapp.GpCaricaIuvResponse gpCaricaIuv(
        @WebParam(partName = "bodyrichiesta", name = "gpCaricaIuv", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/")
        it.govpay.servizi.v2_3.gpapp.GpCaricaIuv bodyrichiesta
    );

    @WebMethod(action = "gpCaricaVersamento")
    @WebResult(name = "gpCaricaVersamentoResponse", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/", partName = "bodyrisposta")
    public it.govpay.servizi.v2_3.gpapp.GpCaricaVersamentoResponse gpCaricaVersamento(
        @WebParam(partName = "bodyrichiesta", name = "gpCaricaVersamento", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/")
        it.govpay.servizi.v2_3.gpapp.GpCaricaVersamento bodyrichiesta,
        @WebParam(partName = "metaInfo", name = "metaInfo", targetNamespace = "http://www.govpay.it/servizi/commons/", header = true)
        it.govpay.servizi.commons.MetaInfo metaInfo
    );

    @WebMethod(action = "gpChiediStatoVersamento")
    @WebResult(name = "gpChiediStatoVersamentoResponse", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/", partName = "bodyrisposta")
    public it.govpay.servizi.v2_3.gpapp.GpChiediStatoVersamentoResponse gpChiediStatoVersamento(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediStatoVersamento", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/")
        it.govpay.servizi.v2_3.gpapp.GpChiediStatoVersamento bodyrichiesta
    );

    @WebMethod(action = "gpChiediListaFlussiRendicontazione")
    @WebResult(name = "gpChiediListaFlussiRendicontazioneResponse", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/", partName = "bodyrisposta")
    public it.govpay.servizi.v2_3.gpapp.GpChiediListaFlussiRendicontazioneResponse gpChiediListaFlussiRendicontazione(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediListaFlussiRendicontazione", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/")
        it.govpay.servizi.v2_3.gpapp.GpChiediListaFlussiRendicontazione bodyrichiesta
    );

    @WebMethod(action = "gpGeneraIuv")
    @WebResult(name = "gpGeneraIuvResponse", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/", partName = "bodyrichiesta")
    public it.govpay.servizi.v2_3.gpapp.GpGeneraIuvResponse gpGeneraIuv(
        @WebParam(partName = "bodyrichiesta", name = "gpGeneraIuv", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/")
        it.govpay.servizi.v2_3.gpapp.GpGeneraIuv bodyrichiesta,
        @WebParam(partName = "metaInfo", name = "metaInfo", targetNamespace = "http://www.govpay.it/servizi/commons/", header = true)
        it.govpay.servizi.commons.MetaInfo metaInfo
    );

    @WebMethod(action = "gpAnnullaVersamento")
    @WebResult(name = "gpAnnullaVersamentoResponse", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/", partName = "bodyrisposta")
    public it.govpay.servizi.v2_3.commons.GpResponse gpAnnullaVersamento(
        @WebParam(partName = "bodyrichiesta", name = "gpAnnullaVersamento", targetNamespace = "http://www.govpay.it/servizi/v2_3/gpApp/")
        it.govpay.servizi.v2_3.gpapp.GpAnnullaVersamento bodyrichiesta
    );
}
