package it.govpay.servizi.v2_5;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-07-04T14:49:50.411+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciGPPrtService", 
                  wsdlLocation = "classpath:wsdl/GpPrt_2.5.wsdl",
                  targetNamespace = "http://www.govpay.it/servizi/v2_5") 
public class PagamentiTelematiciGPPrtService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.govpay.it/servizi/v2_5", "PagamentiTelematiciGPPrtService");
    public final static QName GPPrtPort = new QName("http://www.govpay.it/servizi/v2_5", "GPPrtPort");
    static {
        URL url = PagamentiTelematiciGPPrtService.class.getClassLoader().getResource("wsdl/GpPrt_2.5.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciGPPrtService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GpPrt_2.5.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PagamentiTelematiciGPPrtService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciGPPrtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciGPPrtService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns PagamentiTelematiciGPPrt
     */
    @WebEndpoint(name = "GPPrtPort")
    public PagamentiTelematiciGPPrt getGPPrtPort() {
        return super.getPort(GPPrtPort, PagamentiTelematiciGPPrt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciGPPrt
     */
    @WebEndpoint(name = "GPPrtPort")
    public PagamentiTelematiciGPPrt getGPPrtPort(WebServiceFeature... features) {
        return super.getPort(GPPrtPort, PagamentiTelematiciGPPrt.class, features);
    }

}
