package it.gov.spcoop.nodopagamentispc.servizi.pagamentitelematicirpt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-07-04T14:49:49.676+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT", name = "PagamentiTelematiciRPT")
@XmlSeeAlso({gov.telematici.pagamenti.ws.ppthead.ObjectFactory.class, it.gov.digitpa.schemas._2011.ws.paa.ObjectFactory.class, org.xmlsoap.schemas.soap.envelope.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagamentiTelematiciRPT {

    @WebMethod(action = "nodoInviaRPT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRPTRisposta")
    @WebResult(name = "nodoInviaRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoInviaRPTRisposta nodoInviaRPT(
        @WebParam(partName = "bodyrichiesta", name = "nodoInviaRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoInviaRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazionePPT header
    );

    @WebMethod(action = "nodoChiediInformativaPSP")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediInformativaPSPRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediInformativaPSPRisposta")
    @WebResult(name = "nodoChiediInformativaPSPRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediInformativaPSPRisposta nodoChiediInformativaPSP(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediInformativaPSP", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediInformativaPSP bodyrichiesta
    );

    @WebMethod(action = "nodoChiediQuadraturaPA")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediQuadraturaPARichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediQuadraturaPARisposta")
    @WebResult(name = "nodoChiediQuadraturaPARisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediQuadraturaPARisposta nodoChiediQuadraturaPA(
        @WebParam(partName = "parameters", name = "nodoChiediQuadraturaPA", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediQuadraturaPA parameters
    );

    @WebMethod(action = "nodoInviaRichiestaStorno")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRichiestaStorno", output = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRichiestaStornoRisposta")
    @WebResult(name = "nodoInviaRichiestaStornoRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoInviaRichiestaStornoRisposta nodoInviaRichiestaStorno(
        @WebParam(partName = "parameters", name = "nodoInviaRichiestaStorno", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoInviaRichiestaStorno parameters
    );

    @WebMethod(action = "nodoChiediElencoFlussiRendicontazione")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediElencoFlussiRendicontazioneRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediElencoFlussiRendicontazioneRisposta")
    @WebResult(name = "nodoChiediElencoFlussiRendicontazioneRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediElencoFlussiRendicontazioneRisposta nodoChiediElencoFlussiRendicontazione(
        @WebParam(partName = "parameters", name = "nodoChiediElencoFlussiRendicontazione", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediElencoFlussiRendicontazione parameters
    );

    @WebMethod(action = "nodoChiediCopiaRT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediCopiaRTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediCopiaRTRisposta")
    @WebResult(name = "nodoChiediCopiaRTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediCopiaRTRisposta nodoChiediCopiaRT(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediCopiaRT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediCopiaRT bodyrichiesta
    );

    @WebMethod(action = "nodoInviaCarrelloRPT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaCarrelloRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaCarrelloRPTRisposta")
    @WebResult(name = "nodoInviaCarrelloRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoInviaCarrelloRPTRisposta nodoInviaCarrelloRPT(
        @WebParam(partName = "bodyrichiesta", name = "nodoInviaCarrelloRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoInviaCarrelloRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazioneCarrelloPPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazioneCarrelloPPT header
    );

    @WebMethod(action = "nodoChiediFlussoRendicontazione")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediFlussoRendicontazioneRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediFlussoRendicontazioneRisposta")
    @WebResult(name = "nodoChiediFlussoRendicontazioneRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediFlussoRendicontazioneRisposta nodoChiediFlussoRendicontazione(
        @WebParam(partName = "parameters", name = "nodoChiediFlussoRendicontazione", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediFlussoRendicontazione parameters
    );

    @WebMethod(action = "nodoChiediElencoQuadraturePA")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediElencoQuadraturePARichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediElencoQuadraturePARisposta")
    @WebResult(name = "nodoChiediElencoQuadraturePARisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediElencoQuadraturePARisposta nodoChiediElencoQuadraturePA(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediElencoQuadraturePA", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediElencoQuadraturePA bodyrichiesta
    );

    @WebMethod(action = "nodoChiediListaPendentiRPT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediListaPendentiRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediListaPendentiRPTRisposta")
    @WebResult(name = "nodoChiediListaPendentiRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediListaPendentiRPTRisposta nodoChiediListaPendentiRPT(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediListaPendentiRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediListaPendentiRPT bodyrichiesta
    );

    @WebMethod(action = "nodoChiediSceltaWISP")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediSceltaWISPRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediSceltaWISPRisposta")
    @WebResult(name = "nodoChiediSceltaWISPRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediSceltaWISPRisposta nodoChiediSceltaWISP(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediSceltaWISP", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediSceltaWISP bodyrichiesta
    );

    @WebMethod(action = "nodoChiediStatoRPT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediStatoRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediStatoRPTRisposta")
    @WebResult(name = "nodoChiediStatoRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.paa.NodoChiediStatoRPTRisposta nodoChiediStatoRPT(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediStatoRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.paa.NodoChiediStatoRPT bodyrichiesta
    );
}
