package it.govpay.servizi;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-07-04T14:49:50.154+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciPAService", 
                  wsdlLocation = "classpath:wsdl/GpPa.wsdl",
                  targetNamespace = "http://www.govpay.it/servizi/") 
public class PagamentiTelematiciPAService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.govpay.it/servizi/", "PagamentiTelematiciPAService");
    public final static QName PAPort = new QName("http://www.govpay.it/servizi/", "PAPort");
    static {
        URL url = PagamentiTelematiciPAService.class.getClassLoader().getResource("wsdl/GpPa.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciPAService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GpPa.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PagamentiTelematiciPAService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciPAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciPAService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns PagamentiTelematiciPA
     */
    @WebEndpoint(name = "PAPort")
    public PagamentiTelematiciPA getPAPort() {
        return super.getPort(PAPort, PagamentiTelematiciPA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciPA
     */
    @WebEndpoint(name = "PAPort")
    public PagamentiTelematiciPA getPAPort(WebServiceFeature... features) {
        return super.getPort(PAPort, PagamentiTelematiciPA.class, features);
    }

}
