openapi: 3.0.0
info:
  description: >-
   API di integrazione a GovPay esposte dagli applicativi gestori delle Posizioni Debitorie dell'Ente Creditore per:
    - Notificare i pagamenti effettuati sulla piattaforma pagoPA
    - Verificare i dati delle pendenze oggetto di pagamento
    
   ## Notifica Pagamenti
    La piattaforma GovPay prevede l'invio di una notifica alla conclusione con successo di una transazione di pagamento pagoPA, ovvero a fronte dell'acquisizione di una RT, indipendentemente dalla modalità di pagamento o dall'esito.
    
   ## Verifica Pendenze
    In sede di pagamento, la piattaforma GovPay potrebbe aver necessità di richiedere all'applicativo gestore i dati aggiornati della pendenza oggetto del pagamento. Questo può accadere in due scenari:
    - La pendenza associata al pagamento non è disponibile in GovPay
    - La data di validità presente nella pendenza oggetto del pagamento è decorsa.
    
    Le informazioni restituite dal servizio vanno ad aggiornare la pendenza negli archivi di GovPay ed utilizzate per perfezionare il pagamento. 
  version: "2.0.0"
  title: "GovPay - API Notifica e Verifica"
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - description: Base url servizio
    url: https://host/baseurl
tags:
  - name: Verifica pendenze
  - name: Notifica ricevute
paths:
  '/avvisi/{idDomino}/{numeroAvviso}':
    get:
      operationId: getAvviso
      summary: Verifica di una pendenza da avviso
      tags:
        - Verifica pendenze
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathNumeroAvviso'
      responses:
        '200':
          description: Pendenza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendenzaVerificata'
              examples:
                'Pendenza non eseguita':
                  $ref: 'govpay-api-examples.yaml#/components/examples/PendenzaVerificata'
                'Pendenza annullata':
                  value:
                    stato: 'ANNULLATA'
                    descrizioneStato: 'Pendenza annullata'
                'Pendenza scaduta':
                  value:
                    stato: 'SCADUTA'
                    descrizioneStato: 'Pendenza scaduta'
                'Pendenza sconosciuta':
                  value:
                    stato: 'SCONOSCIUTA'
                    descrizioneStato: 'Pendenza sconosciuta'
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'                
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '404':
          $ref: 'govpay-api-responses.yaml#/components/responses/404NotFound'          
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'
  '/pendenze/{idA2A}/{idPendenza}':
    get:
      operationId: verifyPendenza
      summary: Verifica di una pendenza da identificativo
      tags:
        - Verifica pendenze
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdA2A'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdPendenza'
      responses:
        '200':
          description: Pendenza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendenzaVerificata'
              examples:
                'Pendenza non eseguita':
                  $ref: 'govpay-api-examples.yaml#/components/examples/PendenzaVerificata'
                'Pendenza annullata':
                  value:
                    stato: 'ANNULLATA'
                    descrizioneStato: 'Pendenza annullata'
                'Pendenza scaduta':
                  value:
                    stato: 'SCADUTA'
                    descrizioneStato: 'Pendenza scaduta'
                'Pendenza sconosciuta':
                  value:
                    stato: 'SCONOSCIUTA'
                    descrizioneStato: 'Pendenza sconosciuta'
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '404':
          $ref: 'govpay-api-responses.yaml#/components/responses/404NotFound'          
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable' 
  '/pendenze/{idDomino}/{idTipoPendenza}':
    post:
      operationId: verifyPendenzaMod4
      summary: Acquisizione di una pendenza con dati custom
      tags:
        - Verifica pendenze
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdTipoPendenza'
      requestBody:
        description: Pendenza nel formato custom
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Pendenza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendenzaVerificata'
              examples:
                'Pendenza non eseguita':
                  $ref: 'govpay-api-examples.yaml#/components/examples/PendenzaVerificata'
                'Pendenza annullata':
                  value:
                    stato: 'ANNULLATA'
                    descrizioneStato: 'Pendenza annullata'
                'Pendenza scaduta':
                  value:
                    stato: 'SCADUTA'
                    descrizioneStato: 'Pendenza scaduta'
                'Pendenza sconosciuta':
                  value:
                    stato: 'SCONOSCIUTA'
                    descrizioneStato: 'Pendenza sconosciuta'
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '404':
          $ref: 'govpay-api-responses.yaml#/components/responses/404NotFound'          
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable' 
  '/ricevute/{idDominio}/{iuv}/{idRicevuta}':
    put:
      operationId: notificaRicevuta
      summary: Notifica di una ricevuta di avvenuto pagamento pagoPA
      description: >-
        La notifica di un pagamento corrisponde ad una ricevuta pagoPA, sia questa veicolata nella forma di `RT` o di `recepit`, di esito positivo. 
        Le notifiche sono inviate contestualmente all'evento che le genera. In caso di errori di consegna (ovvero senza risposta HTTP 2xx), le notifiche sono rispedite in tempi successivi. Se la ricevuta risulta gia' stata acquisita, puo' essere ignorata ed esitata con successo per interromperne la rispedizione.
      tags:
        - Notifica ricevute
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIuv'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdRicevuta'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/QueryIdSession'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/QueryIdSessionePortale'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/QueryIdCarrello'
      requestBody:
        description: Notifica di una ricevuta di pagamento
        content:
          application/json:
            schema:
              $ref: 'govpay-api-schemas.yaml#/components/schemas/Ricevuta'
            examples:
              standard:
                $ref: 'govpay-api-examples.yaml#/components/examples/RicevutaEntrata'
      responses:
        '201':
          description: ricevuta di pagamento acquisita
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '404':
          $ref: 'govpay-api-responses.yaml#/components/responses/404NotFound'          
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable' 
components:
  schemas:
    PendenzaVerificata:
      description: >- 
        Il campo 'pendenza' e' obbligatorio quando il valore del campo 'stato' e' uguale a 'NON_ESEGUITA'. Valorizzare il campo 'descrizioneStato' con una descrizione estesa dello stato della pendenza quando il valore del campo 'stato' e' diverso da 'NON_ESEGUITA'.
      type: object
      required: 
        - stato
      properties:
        stato:
          $ref: '#/components/schemas/StatoPendenzaVerificata'   
        descrizioneStato:
          type: string
          description: Descrizione in dettaglio dello stato della pendenza.
        pendenza:
          $ref: 'govpay-api-schemas.yaml#/components/schemas/NuovaPendenza'
    StatoPendenzaVerificata:
      example: NON_ESEGUITA
      type: string
      enum:
        - NON_ESEGUITA
        - ANNULLATA
        - SCADUTA
        - SCONOSCIUTA
