//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://AvvisoPagamentoPA.spcoop.gov.it/InformazioniVersamentoQR", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package itZZ.gov.spcoop.avvisopagamentopa.informazioniversamentoqr;
