-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_fr_1 ON fr  CASCADE;
-- DROP INDEX index_iuv_1 ON iuv  CASCADE;
-- DROP INDEX index_rr_1 ON rr  CASCADE;
-- DROP INDEX index_rpt_2 ON rpt  CASCADE;
-- DROP INDEX index_rpt_1 ON rpt  CASCADE;
-- DROP INDEX index_singoli_versamenti_1 ON singoli_versamenti  CASCADE;
-- DROP INDEX index_versamenti_1 ON versamenti  CASCADE;
-- DROP INDEX index_tributi_1 ON tributi  CASCADE;
-- DROP INDEX index_iban_accredito_1 ON iban_accredito  CASCADE;
-- DROP INDEX index_portali_2 ON portali  CASCADE;
-- DROP INDEX index_portali_1 ON portali  CASCADE;
-- DROP INDEX index_connettori_1 ON connettori  CASCADE;
-- DROP INDEX index_operatori_1 ON operatori  CASCADE;
-- DROP INDEX index_uo_1 ON uo  CASCADE;
-- DROP INDEX index_domini_1 ON domini  CASCADE;
-- DROP INDEX index_applicazioni_2 ON applicazioni  CASCADE;
-- DROP INDEX index_applicazioni_1 ON applicazioni  CASCADE;
-- DROP INDEX index_stazioni_1 ON stazioni  CASCADE;
-- DROP INDEX index_intermediari_1 ON intermediari  CASCADE;
-- DROP INDEX index_canali_1 ON canali  CASCADE;
-- DROP INDEX index_psp_1 ON psp  CASCADE;
DROP TABLE ID_MESSAGGIO_RELATIVO CASCADE;
DROP TABLE rendicontazioni_senza_rpt CASCADE;
DROP TABLE eventi CASCADE;
DROP TABLE pagamenti CASCADE;
DROP TABLE fr_applicazioni CASCADE;
DROP TABLE fr CASCADE;
DROP TABLE iuv CASCADE;
DROP TABLE notifiche CASCADE;
DROP TABLE rr CASCADE;
DROP TABLE rpt CASCADE;
DROP TABLE singoli_versamenti CASCADE;
DROP TABLE versamenti CASCADE;
DROP TABLE applicazioni_domini CASCADE;
DROP TABLE applicazioni_tributi CASCADE;
DROP TABLE tributi CASCADE;
DROP TABLE iban_accredito CASCADE;
DROP TABLE portali_applicazioni CASCADE;
DROP TABLE operatori_portali CASCADE;
DROP TABLE portali CASCADE;
DROP TABLE connettori CASCADE;
DROP TABLE operatori_applicazioni CASCADE;
DROP TABLE operatori_uo CASCADE;
DROP TABLE operatori CASCADE;
DROP TABLE uo CASCADE;
DROP TABLE domini CASCADE;
DROP TABLE applicazioni CASCADE;
DROP TABLE stazioni CASCADE;
DROP TABLE intermediari CASCADE;
DROP TABLE canali CASCADE;
DROP TABLE psp CASCADE;
