INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1211','2','1211','1211','Trasferimenti correnti dallo Stato a destinazione specifica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1212','2','1212','1212','Trasferimenti correnti dallo Stato senza vincolo di destinazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1221','2','1221','1221','Trasferimenti correnti dalla Regione a destinazione specifica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1222','2','1222','1222','Trasferimenti correnti senza vincolo di destinazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1231','2','1231','1231','Trasferimenti correnti da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1232','2','1232','1232','Trasferimenti correnti da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1233','2','1233','1233','Trasferimenti correnti da Città Metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1241','2','1241','1241','Trasferimenti correnti da Enti di previdenza');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1242','2','1242','1242','Trasferimenti correnti da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1243','2','1243','1243','Trasferimenti correnti da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1244','2','1244','1244','Trasferimenti correnti da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1245','2','1245','1245','Trasferimenti correnti da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1246','2','1246','1246','Trasferimenti correnti da Aziende ospedaliero-universitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1247','2','1247','1247','Trasferimenti correnti da Istituti di ricovero e cura a carattere scientifico pubblici (IRCCS)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1248','2','1248','1248','Trasferimenti correnti da Istituti Zooprofilattici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1249','2','1249','1249','Trasferimenti correnti da altri Enti di ricerca');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1250','2','1250','1250','Trasferimenti correnti da Camere di commercio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1251','2','1251','1251','Trasferimenti correnti da Autorità portuali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1252','2','1252','1252','Trasferimenti correnti da Aziende di promozione turistica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1253','2','1253','1253','Trasferimenti correnti da Università');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1254','2','1254','1254','Trasferimenti correnti da Enti Parco Nazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1289','2','1289','1289','Trasferimenti correnti da altre Pubbliche Amministrazioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1291','2','1291','1291','Trasferimenti correnti dall'' Unione europea');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1292','2','1292','1292','Trasferimenti correnti da altri Organismi internazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1293','2','1293','1293','Trasferimenti correnti da Imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1294','2','1294','1294','Trasferimenti correnti da Imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1295','2','1295','1295','Trasferimenti correnti da Istituzioni sociali private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1296','2','1296','1296','Trasferimenti correnti da Famiglie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1301','2','1301','1301','Ricerche e servizi commissionati da amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1302','2','1302','1302','Ricerche e servizi commissionati da Istituzioni internazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1303','2','1303','1303','Ricerche e servizi commissionati da soggetti privati nazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1304','2','1304','1304','Ricerche e servizi commissionati da soggetti privati esteri');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1305','2','1305','1305','Entrate per prestazioni sanitarie ad amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1306','2','1306','1306','Entrate per prestazioni sanitarie a soggetti privati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1307','2','1307','1307','Ricavi dalla vendita di pubblicazioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1308','2','1308','1308','Proventi derivanti dalla prestazione di servizi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1309','2','1309','1309','Realizzi derivanti dalla cessioni di beni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1310','2','1310','1310','IVA a debito');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1321','2','1321','1321','Fitti attivi da terreni e giacimenti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1322','2','1322','1322','Fitti attivi da fabbricati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1323','2','1323','1323','Interessi attivi da Cassa Depositi e Prestiti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1324','2','1324','1324','Interessi e premi su titoli a reddito fisso');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1325','2','1325','1325','Dividendi e altri proventi su titoli azionari e partecipazioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1326','2','1326','1326','Altri interessi attivi su mutui, depositi e conti correnti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1327','2','1327','1327','Altre entrate patrimoniali da beni materiali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1328','2','1328','1328','Entrate patrimoniali da beni immateriali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1331','2','1331','1331','Rimborso spese personale comandato');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1332','2','1332','1332','Recuperi e rimborsi diversi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1341','2','1341','1341','Indennità di assicurazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_1342','2','1342','1342','Altre entrate non classificabili in altre voci');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2111','2','2111','2111','Alienazione di terreni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2112','2','2112','2112','Alienazione di fabbricati residenziali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2113','2','2113','2113','Alienazione di fabbricati non residenziali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2114','2','2114','2114','Alienazione di materiale bibliografico');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2115','2','2115','2115','Alienazione di diritti reali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2116','2','2116','2116','Alienazione di beni immateriali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2119','2','2119','2119','Altre alienazioni di altri beni immobili');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2121','2','2121','2121','Alienazione di beni mobili, macchine e attrezzature');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2129','2','2129','2129','Alienazione di altre immobilizzazioni tecniche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2131','2','2131','2131','Alienazione di partecipazioni a Consorzi, Società, Fondazione o Associazioni di cui al D. Lgs. 127/2003, che appartengono alle Amministrazioni pubbliche.');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2132','2','2132','2132','Alienazione di partecipazioni in altre Amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2133','2','2133','2133','Alienazione di partecipazioni a Consorzi, Società, Fondazione o Associazioni di cui al D. Lgs. 127/2003, che non appartengono alle Amministrazioni pubbliche.');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2138','2','2138','2138','Alienazione di altre partecipazioni nazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2139','2','2139','2139','Alienazione di partecipazioni estere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2141','2','2141','2141','Riscossioni crediti da Regioni e Province autonome');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2142','2','2142','2142','Riscossioni crediti da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2143','2','2143','2143','Riscossioni crediti da Città metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2144','2','2144','2144','Riscossioni crediti da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2145','2','2145','2145','Riscossioni crediti da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2146','2','2146','2146','Riscossioni crediti da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2147','2','2147','2147','Riscossioni crediti da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2148','2','2148','2148','Riscossioni crediti da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2149','2','2149','2149','Riscossioni crediti da Aziende ospedaliero-universitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2150','2','2150','2150','Riscossioni crediti a Istituti zooprofilattici sperimentali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2151','2','2151','2151','Riscossioni crediti da Istituti di ricovero e cura a carattere scientifico (IRCCS) pubblici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2152','2','2152','2152','Riscossioni crediti da altri enti di ricerca');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2189','2','2189','2189','Riscossioni crediti da altre Amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2191','2','2191','2191','Riscossioni di crediti da imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2192','2','2192','2192','Riscossioni crediti da imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2199','2','2199','2199','Riscossioni crediti da altri soggetti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2211','2','2211','2211','Trasferimenti di capitale dallo Stato a destinazione specifica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2212','2','2212','2212','Trasferimenti di capitale dallo Stato senza vincolo di destinazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2221','2','2221','2221','Trasferimenti di capitale dalla Regione a destinazione specifica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2222','2','2222','2222','Trasferimenti di capitale senza vincolo di destinazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2231','2','2231','2231','Trasferimenti di capitale da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2232','2','2232','2232','Trasferimenti di capitale da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2233','2','2233','2233','Trasferimenti di capitale da Città Metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2241','2','2241','2241','Trasferimenti di capitale da Enti di previdenza');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2242','2','2242','2242','Trasferimenti di capitale da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2243','2','2243','2243','Trasferimenti di capitale da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2244','2','2244','2244','Trasferimenti di capitale da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2245','2','2245','2245','Trasferimenti di capitale da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2246','2','2246','2246','Trasferimenti di capitale da Aziende ospedaliero-universitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2247','2','2247','2247','Trasferimenti di capitale da Istituti di ricovero e cura a carattere scientifico (IRCCS) pubblici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2248','2','2248','2248','Trasferimenti di capitale da Istituti Zooprofilattici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2249','2','2249','2249','Trasferimenti di capitale da altri Enti di ricerca');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2250','2','2250','2250','Trasferimenti di capitale da Camere di commercio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2251','2','2251','2251','Trasferimenti di capitale da Autorità portuali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2252','2','2252','2252','Trasferimenti di capitale da Aziende di promozione turistica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2253','2','2253','2253','Trasferimenti di capitale da Università');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2254','2','2254','2254','Trasferimenti di capitale da Enti Parco Nazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2289','2','2289','2289','Trasferimenti di capitale da altre Pubbliche Amministrazioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2291','2','2291','2291','Trasferimenti di capitale dall'' Unione europea');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2292','2','2292','2292','Trasferimenti di capitale da altri Organismi internazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2293','2','2293','2293','Trasferimenti di capitale da Imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2294','2','2294','2294','Trasferimenti di capitale da Imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2295','2','2295','2295','Trasferimenti di capitale da Istituzioni sociali private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2296','2','2296','2296','Trasferimenti di capitale da Famiglie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2311','2','2311','2311','Mutui da Cassa depositi e prestiti - gestione Tesoro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2312','2','2312','2312','Mutui da Cassa depositi e prestiti - gestione CDP spa');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2313','2','2313','2313','Entrate derivanti da operazioni di cartolarizzazione immobiliare (per valori inferiori all''85% del valore del bene)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2314','2','2314','2314','Entrate derivanti da operazioni di cartolarizzazione finanziaria (per valori inferiori all''85% del valore del bene)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2315','2','2315','2315','Mutui e prestiti da Banca Europea degli Investimenti (BEI)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2316','2','2316','2316','Mutui e prestiti da altri - in euro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2317','2','2317','2317','Mutui e prestiti da altri - in altre valute');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2321','2','2321','2321','Anticipazioni di tesoreria');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2331','2','2331','2331','Emissione di titoli obbligazionari in euro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_2332','2','2332','2332','Emissione di titoli obbligazionari in altre valute');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4111','2','4111','4111','Ritenute erariali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4112','2','4112','4112','Ritenute previdenziali e assistenziali al personale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4113','2','4113','4113','Altre ritenute al personale per conto di terzi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4114','2','4114','4114','Rimborso di anticipazione fondo economale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4115','2','4115','4115','Depositi cauzionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4116','2','4116','4116','Crediti v/Erario per Iva');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4117','2','4117','4117','Entrate per Iva "interna"');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4118','2','4118','4118','Entrate per tributi "interni"');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_4999','2','4999','4999','Altre Partite di Giro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_9998','2','9998','9998','INCASSI DA REGOLARIZZARE DERIVANTI DALLE ANTICIPAZIONI DI CASSA (riscossioni codificate dal cassiere/tesoriere)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_X_9999','2','9999','9999','ALTRI INCASSI DA REGOLARIZZARE (riscossioni codificate dal cassiere/tesoriere)');
