INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1211','2','1211','1211','Trasferimenti correnti dallo Stato a destinazione specifica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1212','2','1212','1212','Trasferimenti correnti dallo Stato senza vincolo di destinazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1221','2','1221','1221','Trasferimenti correnti dalla Regione o Provincia autonoma a destinazione specifica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1222','2','1222','1222','Trasferimenti correnti dalla Regione o dalla Provincia autonoma senza vincolo di destinazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1231','2','1231','1231','Trasferimenti correnti da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1232','2','1232','1232','Trasferimenti correnti da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1233','2','1233','1233','Trasferimenti correnti da Città Metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1241','2','1241','1241','Trasferimenti correnti da Enti di previdenza');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1242','2','1242','1242','Trasferimenti correnti da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1243','2','1243','1243','Trasferimenti correnti da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1244','2','1244','1244','Trasferimenti correnti da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1245','2','1245','1245','Trasferimenti correnti da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1246','2','1246','1246','Trasferimenti correnti da Policlinici universitari');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1247','2','1247','1247','Trasferimenti correnti da Istituti di ricovero e cura a carattere scientifico pubblici (IRCCS)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1248','2','1248','1248','Trasferimenti correnti da Istituti Zooprofilattici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1249','2','1249','1249','Trasferimenti correnti da Enti di ricerca statale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1250','2','1250','1250','Trasferimenti correnti da Enti di ricerca locale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1251','2','1251','1251','Trasferimenti correnti da Camere di commercio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1252','2','1252','1252','Trasferimenti correnti da Autorità portuali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1253','2','1253','1253','Trasferimenti correnti da Aziende di promozione turistica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1254','2','1254','1254','Trasferimenti correnti da Università');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1255','2','1255','1255','Trasferimenti correnti da altri Enti Parco');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1257','2','1257','1257','Trasferimenti correnti da altre Pubbliche Amministrazioni centrali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1269','2','1269','1269','Trasferimenti correnti da altre Pubbliche Amministrazioni locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1271','2','1271','1271','Trasferimenti correnti da Imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1272','2','1272','1272','Trasferimenti correnti da Imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1273','2','1273','1273','Trasferimenti correnti da Istituzioni sociali private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1274','2','1274','1274','Trasferimenti correnti da Famiglie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1281','2','1281','1281','Trasferimenti correnti dall'' Unione europea');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1282','2','1282','1282','Contributi e trasferimenti correnti da altre istituzioni estere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1283','2','1283','1283','Contributi e trasferimenti correnti da soggetti esteri privati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1301','2','1301','1301','Ricavi dalla vendita di materiale divulgativo e promozionale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1302','2','1302','1302','Proventi derivanti dai biglietti di ingresso');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1303','2','1303','1303','Proventi dalla vendita di piante di modico valore');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1304','2','1304','1304','IVA a debito');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1318','2','1318','1318','Proventi derivanti da altre cessioni di beni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1319','2','1319','1319','Proventi derivanti da altre prestazioni di servizi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1321','2','1321','1321','Fitti attivi da terreni e giacimenti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1322','2','1322','1322','Fitti attivi da fabbricati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1323','2','1323','1323','Interessi attivi da Amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1324','2','1324','1324','Interessi e premi su titoli a reddito fisso privati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1325','2','1325','1325','Altri interessi attivi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1326','2','1326','1326','Dividendi e altri proventi su titoli azionari e partecipazioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1327','2','1327','1327','Proventi derivanti dall''utilizzo di attrezzature e strutture dell''Ente');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1328','2','1328','1328','Proventi derivanti da autorizzazioni, permessi e concessioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1329','2','1329','1329','Altre entrate patrimoniali da beni materiali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1330','2','1330','1330','Entrate patrimoniali da beni immateriali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1341','2','1341','1341','Rimborso spese personale comandato');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1342','2','1342','1342','Recuperi e rimborsi diversi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1351','2','1351','1351','Indennità di assicurazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1352','2','1352','1352','Proventi da sponsorizzazioni da altre Amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1353','2','1353','1353','Altri proventi da sponsorizzazioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_1354','2','1354','1354','Altre entrate non classificabili in altre voci');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2111','2','2111','2111','Alienazione di terreni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2112','2','2112','2112','Alienazione di fabbricati residenziali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2113','2','2113','2113','Alienazione di fabbricati non residenziali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2114','2','2114','2114','Alienazione di materiale bibliografico');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2115','2','2115','2115','Alienazione di diritti reali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2116','2','2116','2116','Alienazione di beni immateriali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2119','2','2119','2119','Altre alienazioni di altri beni immobili');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2121','2','2121','2121','Alienazione di macchine e attrezzature agricole');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2122','2','2122','2122','Alienazione di beni mobili, macchine e attrezzature');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2123','2','2123','2123','Alienazione di animali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2124','2','2124','2124','Alienazione di piante');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2129','2','2129','2129','Alienazione di altre immobilizzazioni tecniche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2132','2','2132','2132','Alienazione di partecipazioni in altre Amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2138','2','2138','2138','Alienazione di altre partecipazioni nazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2139','2','2139','2139','Alienazione di partecipazioni estere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2141','2','2141','2141','Riscossioni crediti da Regioni e Province autonome');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2142','2','2142','2142','Riscossioni crediti da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2143','2','2143','2143','Riscossioni crediti da Città metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2144','2','2144','2144','Riscossioni crediti da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2145','2','2145','2145','Riscossioni crediti da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2146','2','2146','2146','Riscossioni crediti da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2147','2','2147','2147','Riscossioni crediti da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2148','2','2148','2148','Riscossioni crediti da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2149','2','2149','2149','Riscossioni crediti da Policlinici universitari');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2150','2','2150','2150','Riscossioni crediti da Istituti zooprofilattici sperimentali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2151','2','2151','2151','Riscossioni crediti da Istituti di ricovero e cura a carattere scientifico (IRCCS) pubblici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2152','2','2152','2152','Riscossioni crediti da altri enti di ricerca statali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2153','2','2153','2153','Riscossioni crediti da altri enti di ricerca locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2154','2','2154','2154','Riscossioni crediti da altre Amministrazioni pubbliche centrali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2155','2','2155','2155','Riscossioni crediti da altre Amministrazioni pubbliche locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2156','2','2156','2156','Riscossioni di crediti da imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2157','2','2157','2157','Versamento da compagnia assicuratrice per la liquidazione del TFR');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2192','2','2192','2192','Riscossioni crediti da imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2197','2','2197','2197','Riscossioni crediti da Istituzioni sociali private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2198','2','2198','2198','Riscossioni crediti da Famiglie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2199','2','2199','2199','Riscossione crediti da Estero');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2211','2','2211','2211','Trasferimenti di capitale dallo Stato a destinazione specifica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2212','2','2212','2212','Trasferimenti di capitale dallo Stato senza vincolo di destinazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2221','2','2221','2221','Trasferimenti di capitale dalla Regione o Provincia autonoma a destinazione specifica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2222','2','2222','2222','Trasferimenti di capitale da Regione o Provincia autonoma senza vincolo di destinazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2231','2','2231','2231','Trasferimenti di capitale da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2232','2','2232','2232','Trasferimenti di capitale da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2233','2','2233','2233','Trasferimenti di capitale da Città Metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2241','2','2241','2241','Trasferimenti di capitale da Enti di previdenza');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2242','2','2242','2242','Trasferimenti di capitale da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2243','2','2243','2243','Trasferimenti di capitale da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2244','2','2244','2244','Trasferimenti di capitale da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2245','2','2245','2245','Trasferimenti di capitale da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2246','2','2246','2246','Trasferimenti di capitale da Policlinici universitari');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2247','2','2247','2247','Trasferimenti di capitale da Istituti di ricovero e cura a carattere scientifico (IRCCS) pubblici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2248','2','2248','2248','Trasferimenti di capitale da Istituti Zooprofilattici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2249','2','2249','2249','Trasferimenti di capitale da Enti di ricerca statali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2250','2','2250','2250','Trasferimenti di capitale da altri Enti di ricerca locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2251','2','2251','2251','Trasferimenti di capitale da Camere di commercio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2252','2','2252','2252','Trasferimenti di capitale da Autorità portuali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2253','2','2253','2253','Trasferimenti di capitale da Aziende di promozione turistica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2254','2','2254','2254','Trasferimenti di capitale da Università');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2255','2','2255','2255','Trasferimenti di capitale da altri Enti Parco');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2288','2','2288','2288','Trasferimenti di capitale da altre Pubbliche Amministrazioni centrali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2289','2','2289','2289','Trasferimenti di capitale da altre Pubbliche Amministrazioni locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2291','2','2291','2291','Trasferimenti di capitale dall'' Unione europea');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2292','2','2292','2292','Trasferimenti di capitale da altri Organismi internazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2293','2','2293','2293','Trasferimenti di capitale da Imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2294','2','2294','2294','Trasferimenti di capitale da Imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2295','2','2295','2295','Trasferimenti di capitale da Istituzioni sociali private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2296','2','2296','2296','Trasferimenti di capitale da Famiglie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2311','2','2311','2311','Mutui da Cassa depositi e prestiti - gestione Tesoro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2312','2','2312','2312','Mutui da Cassa depositi e prestiti - gestione CDP spa');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2313','2','2313','2313','Entrate derivanti da operazioni di cartolarizzazione immobiliare (per valori inferiori all''85% del valore del bene)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2314','2','2314','2314','Entrate derivanti da operazioni di cartolarizzazione finanziaria (per valori inferiori all''85% del valore del bene)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2315','2','2315','2315','Mutui e prestiti da Banca Europea degli Investimenti (BEI)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2316','2','2316','2316','Mutui e prestiti da altri - in euro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2317','2','2317','2317','Mutui e prestiti da altri - in altre valute');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2321','2','2321','2321','Anticipazioni di tesoreria');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2331','2','2331','2331','Emissione di titoli obbligazionari in euro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_2332','2','2332','2332','Emissione di titoli obbligazionari in altre valute');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_3101','2','3101','3101','Ritenute erariali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_3102','2','3102','3102','Ritenute previdenziali e assistenziali al personale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_3103','2','3103','3103','Altre ritenute al personale per conto di terzi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_3104','2','3104','3104','Rimborso di anticipazione fondo economale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_3105','2','3105','3105','Prelievi da conti bancari di deposito');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_3106','2','3106','3106','Depositi cauzionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_3107','2','3107','3107','Crediti v/Erario per Iva');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_3199','2','3199','3199','Altre Partite di Giro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_9998','2','9998','9998','INCASSI DA REGOLARIZZARE DERIVANTI DALLE ANTICIPAZIONI DI CASSA (riscossioni codificate dal cassiere/tesoriere)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_P_9999','2','9999','9999','ALTRI INCASSI DA REGOLARIZZARE (riscossioni codificate dal cassiere/tesoriere)');
