package it.gov.spcoop.nodopagamentispc.servizi.pagamentitelematicirpt;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-07-04T14:49:49.704+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciRPTservice", 
                  wsdlLocation = "classpath:wsdl/NodoPerPa.wsdl",
                  targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT") 
public class PagamentiTelematiciRPTservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT", "PagamentiTelematiciRPTservice");
    public final static QName PagamentiTelematiciRPTPort = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT", "PagamentiTelematiciRPTPort");
    static {
        URL url = PagamentiTelematiciRPTservice.class.getClassLoader().getResource("wsdl/NodoPerPa.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciRPTservice.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/NodoPerPa.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PagamentiTelematiciRPTservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciRPTservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciRPTservice() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns PagamentiTelematiciRPT
     */
    @WebEndpoint(name = "PagamentiTelematiciRPTPort")
    public PagamentiTelematiciRPT getPagamentiTelematiciRPTPort() {
        return super.getPort(PagamentiTelematiciRPTPort, PagamentiTelematiciRPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciRPT
     */
    @WebEndpoint(name = "PagamentiTelematiciRPTPort")
    public PagamentiTelematiciRPT getPagamentiTelematiciRPTPort(WebServiceFeature... features) {
        return super.getPort(PagamentiTelematiciRPTPort, PagamentiTelematiciRPT.class, features);
    }

}
