package it.govpay.servizi;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2022-01-10T10:35:56.834+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciGPPrtService", 
                  wsdlLocation = "classpath:wsdl/GpPrt.wsdl",
                  targetNamespace = "http://www.govpay.it/servizi/") 
public class PagamentiTelematiciGPPrtService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.govpay.it/servizi/", "PagamentiTelematiciGPPrtService");
    public final static QName GPPrtPort = new QName("http://www.govpay.it/servizi/", "GPPrtPort");
    static {
        URL url = PagamentiTelematiciGPPrtService.class.getClassLoader().getResource("wsdl/GpPrt.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciGPPrtService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GpPrt.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PagamentiTelematiciGPPrtService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciGPPrtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciGPPrtService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns PagamentiTelematiciGPPrt
     */
    @WebEndpoint(name = "GPPrtPort")
    public PagamentiTelematiciGPPrt getGPPrtPort() {
        return super.getPort(GPPrtPort, PagamentiTelematiciGPPrt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciGPPrt
     */
    @WebEndpoint(name = "GPPrtPort")
    public PagamentiTelematiciGPPrt getGPPrtPort(WebServiceFeature... features) {
        return super.getPort(GPPrtPort, PagamentiTelematiciGPPrt.class, features);
    }

}
