package it.govpay.servizi;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2022-01-10T10:35:56.655+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciGPAppService", 
                  wsdlLocation = "classpath:wsdl/GpApp.wsdl",
                  targetNamespace = "http://www.govpay.it/servizi/") 
public class PagamentiTelematiciGPAppService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.govpay.it/servizi/", "PagamentiTelematiciGPAppService");
    public final static QName GPAppPort = new QName("http://www.govpay.it/servizi/", "GPAppPort");
    static {
        URL url = PagamentiTelematiciGPAppService.class.getClassLoader().getResource("wsdl/GpApp.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciGPAppService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GpApp.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PagamentiTelematiciGPAppService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciGPAppService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciGPAppService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns PagamentiTelematiciGPApp
     */
    @WebEndpoint(name = "GPAppPort")
    public PagamentiTelematiciGPApp getGPAppPort() {
        return super.getPort(GPAppPort, PagamentiTelematiciGPApp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciGPApp
     */
    @WebEndpoint(name = "GPAppPort")
    public PagamentiTelematiciGPApp getGPAppPort(WebServiceFeature... features) {
        return super.getPort(GPAppPort, PagamentiTelematiciGPApp.class, features);
    }

}
