package it.govpay.servizi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2022-01-10T10:35:56.831+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.govpay.it/servizi/", name = "PagamentiTelematiciGPPrt")
@XmlSeeAlso({it.govpay.servizi.commons.ObjectFactory.class, it.govpay.servizi.gpprt.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagamentiTelematiciGPPrt {

    @WebMethod(action = "gpAvviaTransazionePagamento")
    @WebResult(name = "gpAvviaTransazionePagamentoResponse", targetNamespace = "http://www.govpay.it/servizi/gpPrt/", partName = "bodyrisposta")
    public it.govpay.servizi.gpprt.GpAvviaTransazionePagamentoResponse gpAvviaTransazionePagamento(
        @WebParam(partName = "bodyrichiesta", name = "gpAvviaTransazionePagamento", targetNamespace = "http://www.govpay.it/servizi/gpPrt/")
        it.govpay.servizi.gpprt.GpAvviaTransazionePagamento bodyrichiesta,
        @WebParam(partName = "metaInfo", name = "metaInfo", targetNamespace = "http://www.govpay.it/servizi/commons/", header = true)
        it.govpay.servizi.commons.MetaInfo metaInfo
    );

    @WebMethod(action = "gpChiediListaPsp")
    @WebResult(name = "gpChiediListaPspResponse", targetNamespace = "http://www.govpay.it/servizi/gpPrt/", partName = "bodyrisposta")
    public it.govpay.servizi.gpprt.GpChiediListaPspResponse gpChiediListaPsp(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediListaPsp", targetNamespace = "http://www.govpay.it/servizi/gpPrt/")
        it.govpay.servizi.gpprt.GpChiediListaPsp bodyrichiesta
    );

    @WebMethod(action = "gpChiediStatoTransazione")
    @WebResult(name = "gpChiediStatoTransazioneResponse", targetNamespace = "http://www.govpay.it/servizi/gpPrt/", partName = "bodyrisposta")
    public it.govpay.servizi.gpprt.GpChiediStatoTransazioneResponse gpChiediStatoTransazione(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediStatoTransazione", targetNamespace = "http://www.govpay.it/servizi/gpPrt/")
        it.govpay.servizi.gpprt.GpChiediStatoTransazione bodyrichiesta
    );

    @WebMethod(action = "gpChiediSceltaWisp")
    @WebResult(name = "gpChiediSceltaWispResponse", targetNamespace = "http://www.govpay.it/servizi/gpPrt/", partName = "bodyrisposta")
    public it.govpay.servizi.gpprt.GpChiediSceltaWispResponse gpChiediSceltaWisp(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediSceltaWisp", targetNamespace = "http://www.govpay.it/servizi/gpPrt/")
        it.govpay.servizi.gpprt.GpChiediSceltaWisp bodyrichiesta
    );

    @WebMethod(action = "gpChiediStatoVersamento")
    @WebResult(name = "gpChiediStatoVersamentoResponse", targetNamespace = "http://www.govpay.it/servizi/gpPrt/", partName = "bodyrisposta")
    public it.govpay.servizi.gpprt.GpChiediStatoVersamentoResponse gpChiediStatoVersamento(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediStatoVersamento", targetNamespace = "http://www.govpay.it/servizi/gpPrt/")
        it.govpay.servizi.gpprt.GpChiediStatoVersamento bodyrichiesta
    );

    @WebMethod(action = "gpAvviaRichiestaStorno")
    @WebResult(name = "gpAvviaRichiestaStornoResponse", targetNamespace = "http://www.govpay.it/servizi/gpPrt/", partName = "bodyrisposta")
    public it.govpay.servizi.gpprt.GpAvviaRichiestaStornoResponse gpAvviaRichiestaStorno(
        @WebParam(partName = "bodyrichiesta", name = "gpAvviaRichiestaStorno", targetNamespace = "http://www.govpay.it/servizi/gpPrt/")
        it.govpay.servizi.gpprt.GpAvviaRichiestaStorno bodyrichiesta
    );

    @WebMethod(action = "gpChiediListaVersamenti")
    @WebResult(name = "gpChiediListaVersamentiResponse", targetNamespace = "http://www.govpay.it/servizi/gpPrt/", partName = "bodyrisposta")
    public it.govpay.servizi.gpprt.GpChiediListaVersamentiResponse gpChiediListaVersamenti(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediListaVersamenti", targetNamespace = "http://www.govpay.it/servizi/gpPrt/")
        it.govpay.servizi.gpprt.GpChiediListaVersamenti bodyrichiesta
    );

    @WebMethod(action = "gpChiediStatoRichiestaStorno")
    @WebResult(name = "gpChiediStatoRichiestaStornoResponse", targetNamespace = "http://www.govpay.it/servizi/gpPrt/", partName = "bodyrisposta")
    public it.govpay.servizi.gpprt.GpChiediStatoRichiestaStornoResponse gpChiediStatoRichiestaStorno(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediStatoRichiestaStorno", targetNamespace = "http://www.govpay.it/servizi/gpPrt/")
        it.govpay.servizi.gpprt.GpChiediStatoRichiestaStorno bodyrichiesta
    );
}
