package it.govpay.servizi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2022-01-10T10:35:57.111+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.govpay.it/servizi/", name = "PagamentiTelematiciGPRnd")
@XmlSeeAlso({it.govpay.servizi.gprnd.ObjectFactory.class, it.govpay.servizi.commons.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagamentiTelematiciGPRnd {

    @WebMethod(action = "gpChiediFlussoRendicontazione")
    @WebResult(name = "gpChiediFlussoRendicontazioneResponse", targetNamespace = "http://www.govpay.it/servizi/gpRnd/", partName = "bodyrisposta")
    public it.govpay.servizi.gprnd.GpChiediFlussoRendicontazioneResponse gpChiediFlussoRendicontazione(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediFlussoRendicontazione", targetNamespace = "http://www.govpay.it/servizi/gpRnd/")
        it.govpay.servizi.gprnd.GpChiediFlussoRendicontazione bodyrichiesta
    );

    @WebMethod(action = "gpChiediListaFlussiRendicontazione")
    @WebResult(name = "gpChiediListaFlussiRendicontazioneResponse", targetNamespace = "http://www.govpay.it/servizi/gpRnd/", partName = "bodyrisposta")
    public it.govpay.servizi.gprnd.GpChiediListaFlussiRendicontazioneResponse gpChiediListaFlussiRendicontazione(
        @WebParam(partName = "bodyrichiesta", name = "gpChiediListaFlussiRendicontazione", targetNamespace = "http://www.govpay.it/servizi/gpRnd/")
        it.govpay.servizi.gprnd.GpChiediListaFlussiRendicontazione bodyrichiesta
    );
}
