package it.govpay.servizi;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2022-01-10T10:35:57.114+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciGPRndService", 
                  wsdlLocation = "classpath:wsdl/GpRnd.wsdl",
                  targetNamespace = "http://www.govpay.it/servizi/") 
public class PagamentiTelematiciGPRndService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.govpay.it/servizi/", "PagamentiTelematiciGPRndService");
    public final static QName GPRndPort = new QName("http://www.govpay.it/servizi/", "GPRndPort");
    static {
        URL url = PagamentiTelematiciGPRndService.class.getClassLoader().getResource("wsdl/GpRnd.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciGPRndService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GpRnd.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PagamentiTelematiciGPRndService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciGPRndService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciGPRndService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns PagamentiTelematiciGPRnd
     */
    @WebEndpoint(name = "GPRndPort")
    public PagamentiTelematiciGPRnd getGPRndPort() {
        return super.getPort(GPRndPort, PagamentiTelematiciGPRnd.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciGPRnd
     */
    @WebEndpoint(name = "GPRndPort")
    public PagamentiTelematiciGPRnd getGPRndPort(WebServiceFeature... features) {
        return super.getPort(GPRndPort, PagamentiTelematiciGPRnd.class, features);
    }

}
