package it.gov.spcoop.nodopagamentispc.servizi.pagamentitelematiciccp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-07-04T14:49:49.999+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP", name = "PagamentiTelematiciCCP")
@XmlSeeAlso({gov.telematici.pagamenti.ws.ppthead.ObjectFactory.class, it.gov.digitpa.schemas._2011.pagamenti.revoche.ObjectFactory.class, it.gov.digitpa.schemas._2011.pagamenti.ObjectFactory.class, it.gov.digitpa.schemas._2011.ws.psp.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagamentiTelematiciCCP {

    @WebMethod(action = "paaVerificaRPT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaVerificaRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaVerificaRPTRisposta")
    @WebResult(name = "paaVerificaRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.psp.PaaVerificaRPTRisposta paaVerificaRPT(
        @WebParam(partName = "bodyrichiesta", name = "paaVerificaRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.psp.PaaVerificaRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazionePPT header
    );

    @WebMethod(action = "paaAttivaRPT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaAttivaRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaAttivaRPTRisposta")
    @WebResult(name = "paaAttivaRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public it.gov.digitpa.schemas._2011.ws.psp.PaaAttivaRPTRisposta paaAttivaRPT(
        @WebParam(partName = "bodyrichiesta", name = "paaAttivaRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        it.gov.digitpa.schemas._2011.ws.psp.PaaAttivaRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazionePPT header
    );
}
