# This file contains reusable openapi-v3 entities for defining
#   interoperable API behavior by adopting developers.
#
# You can reference components via JSON-refs https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03
#  eg. $ref: 'https://gigantic-server.com/schemas/Monster/schema.json'
#
openapi: 3.0.0
components:
  schemas:
    Dominio:
      type: object
      required:
        - idDominio
        - ragioneSociale
      properties:
        idDominio:
          type: string
          description: Codice fiscale
          example: 01234567890
          minLength: 1
          maxLength: 35          
        ragioneSociale:
          type: string
          description: Ragione sociale
          example: Ufficio due
          minLength: 1
          maxLength: 70          
        indirizzo:
          type: string
          example: Piazza della Vittoria
          minLength: 1
          maxLength: 70
        civico:
          type: string
          example: 10/A
          minLength: 1
          maxLength: 16
        cap:
          type: string
          example: 00000
          minLength: 1
          maxLength: 16
        localita:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        provincia:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        nazione:
          type: string
          example: IT
          pattern: "[A-Z]{2,2}"
        email:
          type: string
          description: Posta elettronica ordinaria
          example:  peo@creditore.it  
          pattern: "[A-Za-z0-9_]+([\\-\\+\\.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*\\.[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*"          
        pec:
          type: string
          description: Posta elettronica certificata
          example:  peo@creditore.it  
          pattern: "[A-Za-z0-9_]+([\\-\\+\\.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*\\.[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*" 
        tel:
          type: string
          description: Numero di telefono dell'help desk di primo livello
          example: 021234567890  
        fax:
          type: string
          description: Numero di fax dell'help desk di primo livello
          example: 021234567890           
        web:
          type: string
          description: Url del sito web
          example: http://www.comune.it/
        gln:
          type: string
          description: Global location number del beneficiario
          example: 0011223344556
        cbill:
          type: string
          description: codice cbill del beneficiario
          example: 12345
        logo:
          type: string
          description: URL del logo
          example: http://.../domini/01234567890/logo
    UnitaOperativa:
      type: object
      required: 
        - ragioneSociale
      properties:
        idUnitaOperativa:
          type: string
          description: Codice fiscale
          example: 01234567890
          minLength: 1
          maxLength: 35          
        ragioneSociale:
          type: string
          description: Ragione sociale
          example: Ufficio due
          minLength: 1
          maxLength: 70          
        indirizzo:
          type: string
          example: Piazza della Vittoria
          minLength: 1
          maxLength: 70
        civico:
          type: string
          example: 10/A
          minLength: 1
          maxLength: 16
        cap:
          type: string
          example: 00000
          minLength: 1
          maxLength: 16
        localita:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        provincia:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        nazione:
          type: string
          example: IT
          pattern: "[A-Z]{2,2}"
        email:
          type: string
          description: Posta elettronica ordinaria
          example:  peo@creditore.it  
          pattern: "[A-Za-z0-9_]+([\\-\\+\\.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*\\.[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*"          
        pec:
          type: string
          description: Posta elettronica certificata
          example:  peo@creditore.it  
          pattern: "[A-Za-z0-9_]+([\\-\\+\\.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*\\.[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*" 
        tel:
          type: string
          description: Numero di telefono dell'help desk di primo livello
          example: 021234567890  
        fax:
          type: string
          description: Numero di fax dell'help desk di primo livello
          example: 021234567890           
        web:
          type: string
          description: Url del sito web
          example: http://www.comune.it/
        area:
          type: string
          description: Nome dell'area di competenza
          example: Affari generali e istituzionali  
    Soggetto:
      description: dati anagrafici di un versante o pagatore.
      type: object
      required:
        - tipo
        - identificativo
      properties:
        tipo:
          $ref: "#/components/schemas/TipoSoggetto"
        identificativo:
          description: codice fiscale o partita iva del soggetto
          type: string
          example: RSSMRA30A01H501I
          minLength: 1
          maxLength: 35
        anagrafica:
          description: nome e cognome o altra ragione sociale del soggetto
          type: string
          example: Mario Rossi
          minLength: 1
          maxLength: 70
        indirizzo:
          type: string
          example: Piazza della Vittoria
          minLength: 1
          maxLength: 70
        civico:
          type: string
          example: 10/A
          minLength: 1
          maxLength: 16
        cap:
          type: string
          example: 00000
          minLength: 1
          maxLength: 16
        localita:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        provincia:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        nazione:
          type: string
          example: IT
          pattern: "[A-Z]{2,2}"
        email:
          type: string
          example: mario.rossi@host.eu
          pattern: "[A-Za-z0-9_]+([\\-\\+\\.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*\\.[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*"
        cellulare:
          type: string
          example: +39 000 1234567    
          pattern: "\\+[0-9]{2,2}\\s[0-9]{3,3}\\-[0-9]{7,7}" 
    Conto:
      type: object
      required:
        - iban
      properties:
        iban:
          type: string
          example: IT60X0542811101000000123456
          pattern: "[a-zA-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}" 
        bic:
          type: string
          example: DABAIE2D
          pattern: "[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}"
    TipoSoggetto:
      description: >-
        tipologia di soggetto, se persona fisica (F) o giuridica
        (G)
      type: string
      enum:
        - G
        - F
      example: F   
    Segnalazione:
      type: object
      required:
        - codice
        - descrizione
      properties:
        data:
          type: string
          format: date
          example: '2018-12-31'
        codice:
          type: string
          example: '0013'
        descrizione:
          type: string   
          example: 'Pagamento rendicontato senza RPT'
        dettaglio:
          type: string
          example: 'Acquisita rendicontazione senza RPT nel flusso ABC-1234-DEFG' 
    Acl:
      type: object
      required:
        - servizi
        - autorizzazioni
      properties:
        ruolo:
          type: string
          description: ruolo a cui si applica l'acl
          example: Operatore
        principal:
          type: string
          description: principal a cui si applica l'acl
          example: user001
        servizi:
          $ref: "#/components/schemas/TipoServizio"
        autorizzazioni:
          $ref: "#/components/schemas/TipoAutorizzazione"
    TipoServizio:
      type: string
      description: >- 
        Servizio oggetto dell'autorizzazione
         * Anagrafica PagoPA
         * Anagrafica Creditore
         * Anagrafica Applicazioni
         * Anagrafica Ruoli
         * Pendenze e Pagamenti
         * Pendenze e Pagamenti propri 
         * Rendicontazioni e Incassi
         * Giornale degli Eventi
         * Statistiche
         * Configurazione e Manutenzione
      enum:
        - Anagrafica PagoPA
        - Anagrafica Creditore
        - Anagrafica Applicazioni
        - Anagrafica Ruoli
        - Pagamenti e Pendenze
        - Rendicontazioni e Incassi
        - Giornale degli Eventi
        - Configurazione e manutenzione
      example:
        Pendenze e Pagamenti   
    TipoAutorizzazione:
      type: array
      items:
        type: string
        enum:
         - Lettura
         - Scrittura
         - Esecuzione
      example:
        - Lettura
        - Scrittura                             
    Profilo:
      type: object
      required: 
        - nome
        - domini
        - entrate
        - acl
      properties:
        nome:
          type: string
          description: Nome o principal dell'utenza
        domini:
          type: array
          description: domini su cui e' abilitato ad operare
          items: 
            $ref: '#/components/schemas/Dominio'
        entrate:
          type: array
          description: entrate su cui e' abilitato ad operare
          items: 
            $ref: '#/components/schemas/TipoEntrata'
        acl:
          type: array
          items:
            $ref: '#/components/schemas/Acl'
        anagrafica:
          $ref: '#/components/schemas/Soggetto'
        identityData:
          type: object     
    TipoEntrata:
      type: object
      required:
       - idEntrata
       - tipoContabilita
       - codiceContabilita
      properties:
        idEntrata:
          type: string
          example: IMU
        tipoContabilita:
          $ref: '#/components/schemas/TipoContabilita'
        codiceContabilita:
          description: Codifica del capitolo di bilancio
          type: string
          example: 3321
        abilitato:
          type: boolean
          description: Indicazione l'entrata e' abilitata
          example: true
          default: true
    TipoContabilita:
      description: Tipologia di codifica del capitolo di bilancio
      type: string
      enum:
        - CAPITOLO
        - SPECIALE
        - SIOPE
        - ALTRO
      example: SIOPE
    TassonomiaAvviso:
      description: Macro categoria della pendenza Agid
      type: string
      enum:
        - Cartelle esattoriali
        - Diritti e concessioni
        - Imposte e tasse
        - IMU, TASI e altre tasse comunali
        - Ingressi a mostre e musei
        - Multe e sanzioni amministrative
        - Previdenza e infortuni
        - Servizi erogati dal comune
        - Servizi erogati da altri enti
        - Servizi scolastici
        - Tassa automobilistica
        - Ticket e prestazioni sanitarie
        - Trasporti, mobilità e parcheggi
      example: 
        Ticket e prestazioni sanitarie
    StatoVocePendenza:
      type: string
      description: Stato della voce di pagamento
      enum:
        - Eseguito 
        - Non eseguito
        - Anomalo  
    StatoPendenza:
      example: NON_ESEGUITO
      type: string
      enum:
        - ESEGUITA
        - NON_ESEGUITA
        - ESEGUITA_PARZIALE
        - ANNULLATA
        - SCADUTA
      description: >-
        Stato della pendenza: 
         * ESEGUITA: Pagata
         * NON_ESEGUITA: Da pagare
         * ESEGUITA_PARZIALE: Pagata parzialmente
         * ANNULLATA: Annullata
         * SCADUTA: Scaduta 
    StatoAvviso:
      description: Stato dell'avviso
      example: Non pagato
      type: string
      enum:
        - Pagato
        - Non pagato
        - Scaduto
        - Annullato                     
    TipoAutenticazioneSoggetto:
      type: string
      enum:
        - CNS
        - USR
        - OTH
        - N/A
      description: modalita' di autenticazione del soggetto versante
    StatoPagamento:
      type: string
      example: ESEGUITO
      enum:
        - IN_CORSO
        - ESEGUITO
        - NON_ESEGUITO
        - ESEGUITO_PARZIALE
        - ANNULLATO
        - FALLITO
      description: > 
        Stato del pagamento
         * IN_CORSO: Pagamento in corso
         * ANNULLATO: Pagamento annullato dall'utente o scaduto per timeout
         * FALLITO: Pagamento non perfezionato per errori della piattaforma
         * ESEGUITO: Pagamento concluso con successo
         * NON_ESEGUITO: Processo concluso senza il perfezionamento del pagamento
         * ESEGUITO_PARZIALE: Pagamento parzialmente eseguito
    EsitoRpp:
      example: ESEGUITO
      type: string
      enum:
        - IN_CORSO
        - RIFIUTATO
        - ESEGUITO
        - NON_ESEGUITO
        - ESEGUITO_PARZIALE
        - DECORRENZA
        - DECORENNZA_PARZIALE
      description: > 
        Esito della richiesta di pagamento:
         * IN_CORSO: Pagamento in corso
         * RIFIUTATO: Pagamento rifiutato
         * ESEGUITO: Pagamento eseguito
         * NON_ESEGUITO: Pagamento non eseguito
         * ESEGUITO_PARZIALE: Pagamento parzialmente eseguito
         * DECORRENZA: Decorrenza termini
         * DECORRENZA_PARZIALE: Decorrenza termini parziale                              