package it.govpay.ragioneria.v3.api;

import java.util.List;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;
import javax.ws.rs.DefaultValue;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import it.govpay.ragioneria.v3.beans.FaultBean;
import it.govpay.ragioneria.v3.beans.Riscossione;
import it.govpay.ragioneria.v3.beans.Riscossioni;

/**
 * GovPay - API Ragioneria
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
@Path("/")
public interface RiscossioniApi  {

    /**
     * Elenco degli importi riscossi o stornati
     *
     */
    @GET
    @Path("/riscossioni")
    @Produces({ "application/json" })
    @Operation(summary = "Elenco degli importi riscossi o stornati", tags={ "Riscossioni" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Dettaglio della riscossione", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Riscossioni.class))),
        @ApiResponse(responseCode = "400", description = "Richiesta non correttamente formata", content = @Content(mediaType = "application/json", schema = @Schema(implementation = FaultBean.class))),
        @ApiResponse(responseCode = "401", description = "Richiesta non autenticata"),
        @ApiResponse(responseCode = "403", description = "Richiesta non autorizzata"),
        @ApiResponse(responseCode = "500", description = "Servizio non disponibile", content = @Content(mediaType = "application/json", schema = @Schema(implementation = FaultBean.class))) })
    public Response findRiscossioni(@QueryParam("pagina")  @DefaultValue("1") Integer pagina, @QueryParam("risultatiPerPagina") @Max(200) @DefaultValue("25") Integer risultatiPerPagina, @QueryParam("campi") String campi, @QueryParam("ordinamento") String ordinamento, @QueryParam("idDominio") @Pattern(regexp="(^([0-9]){11}$)") String idDominio, @QueryParam("dataDa") String dataDa, @QueryParam("dataA") String dataA, @QueryParam("stato") String stato, @QueryParam("tipo") List<String> tipo, @QueryParam("metadatiPaginazione") @DefaultValue("true") Boolean metadatiPaginazione, @QueryParam("maxRisultati") @DefaultValue("true") Boolean maxRisultati);

    /**
     * Dettaglio di una riscossione
     *
     */
    @GET
    @Path("/riscossioni/{idDominio}/{iuv}/{iur}/{indice}")
    @Produces({ "application/json" })
    @Operation(summary = "Dettaglio di una riscossione", tags={ "Riscossioni" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Dettaglio della riscossione", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Riscossione.class))),
        @ApiResponse(responseCode = "401", description = "Richiesta non autenticata"),
        @ApiResponse(responseCode = "403", description = "Richiesta non autorizzata"),
        @ApiResponse(responseCode = "404", description = "Richiesta non correttamente formata", content = @Content(mediaType = "application/json", schema = @Schema(implementation = FaultBean.class))),
        @ApiResponse(responseCode = "500", description = "Servizio non disponibile", content = @Content(mediaType = "application/json", schema = @Schema(implementation = FaultBean.class))) })
    public Response getRiscossione(@PathParam("idDominio") @Pattern(regexp="(^([0-9]){11}$)") String idDominio, @PathParam("iuv") String iuv, @PathParam("iur") String iur, @PathParam("indice") @Min(1) @Max(5) Integer indice);
}
