# stage sorgente da utilizzare per il build dell'immagine finale
ARG govpay_fullversion
ARG source_image
ARG govpay_home=/etc/govpay
ARG govpay_log=/var/log/govpay

# Trasformo l'argomento di build source_image in un nome di stage (da usare su COPY --from=...)
FROM ${source_image} AS source_image_full


FROM alpine:latest AS source_image_built
LABEL org.opencontainers.image.authors="manca@link.it"
LABEL org.opencontainers.image.description="Immagine utilizzata per il deploy dei nodi"
ARG govpay_fullversion
ARG govpay_home
ARG govpay_log
ARG vcs_ref=

USER root
ENV GOVPAY_HOME=${govpay_home} \
JAVA_HOME=/usr/lib/jvm/java-21-openjdk \
GOVPAY_HOME_HTTPS=${govpay_home}_https \
GOVPAY_LOGDIR=${govpay_log} \
GOVPAY_FULLVERSION=${govpay_fullversion} \
HSQLDB_FULLVERSION=2.7.4 \
POSTGRES_JDBC_VERSION=42.7.5 \
TOMCAT_VERSION=11.0.25 \
CATALINA_HOME=/usr/local/tomcat \
TZ="Europe/Rome"

# Provenienza OCI: version = versione prodotto GovPay; revision = git sha del repo docker;
# tomcat.version tracciato dall'ENV (motivo tipico dei ribuild a prodotto invariato)
LABEL org.opencontainers.image.version="${GOVPAY_FULLVERSION}" \
      org.opencontainers.image.revision="${vcs_ref}" \
      it.govpay.tomcat.version="${TOMCAT_VERSION}"



RUN set -eux; \
mkdir -p ${GOVPAY_HOME} ${GOVPAY_HOME_HTTPS} ${GOVPAY_LOGDIR};  \
apk update; \
apk upgrade; \
apk add --no-cache curl openjdk21-jre tar netcat-openbsd unzip xmlstarlet bash fontconfig ttf-dejavu; \
rm -rf /var/cache/apk/*; \
echo "${TZ}" > /etc/timezone; \
addgroup -S tomcat; \
adduser -S -G tomcat -h ${CATALINA_HOME} -s /bin/false tomcat; \
curl -kL -sS -q -o /var/tmp/hsqldb-${HSQLDB_FULLVERSION}.zip https://sourceforge.net/projects/hsqldb/files/hsqldb/hsqldb_2_7/hsqldb-${HSQLDB_FULLVERSION}.zip/download; \
unzip -q -d /opt /var/tmp/hsqldb-${HSQLDB_FULLVERSION}.zip hsqldb-${HSQLDB_FULLVERSION}/hsqldb/lib/*; \
rm -f  /var/tmp/hsqldb-${HSQLDB_FULLVERSION}.zip; \
curl -fsSL https://downloads.apache.org/tomcat/tomcat-${TOMCAT_VERSION%%.*}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz  -o apache-tomcat-${TOMCAT_VERSION}.tar.gz; \
curl -fsSL https://downloads.apache.org/tomcat/tomcat-${TOMCAT_VERSION%%.*}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz.sha512 -o SHA512; \
sha512sum -c SHA512; \
tar -xzC /usr/local -f apache-tomcat-${TOMCAT_VERSION}.tar.gz \
&& mv /usr/local/apache-tomcat-${TOMCAT_VERSION}/* ${CATALINA_HOME} \
&& rmdir /usr/local/apache-tomcat-${TOMCAT_VERSION} \
&& rm -rf ${CATALINA_HOME}/webapps/* apache-tomcat-${TOMCAT_VERSION}.tar.gz SHA512 \
&& chmod +x ${CATALINA_HOME}/bin/*.sh

# -XX:+PrintFlagsFinal \
ENV CATALINA_OPTS="-server \
-XX:+UseContainerSupport \
-XX:+UseG1GC \
-XX:+DisableExplicitGC \
-XX:+UnlockExperimentalVMOptions \
-Djava.net.preferIPv4Stack=true \
-Djava.awt.headless=true \
-Duser.language=it \
-Duser.country=IT \
-Dfile.encoding=UTF-8"

ARG source_image
ARG govpay_archives_type=all
ENV GOVPAY_BUILT_FROM=${source_image}:${govpay_fullversion} \
GOVPAY_ARCHIVES_TYPE=${govpay_archives_type} 
ARG govpay_database_vendor=hsql
ENV GOVPAY_DB_TYPE=${govpay_database_vendor}

COPY --from=source_image_full --chown=tomcat:0 /opt/govpay-installer-${GOVPAY_FULLVERSION}/dist/archivi/* ${CATALINA_HOME}/webapps/
COPY --from=source_image_full --chown=tomcat:0 /opt/govpay-installer-${GOVPAY_FULLVERSION}/dist/sql/* /opt/${govpay_database_vendor}
COPY --from=source_image_full --chown=0:0 /opt/change_dir_perms /usr/local/bin/
COPY --from=source_image_full --chown=tomcat:0 /opt/TomcatConfigCli.class /usr/local/bin/it/link/
COPY --from=source_image_full --chown=tomcat:0 /opt/govpay-installer-${GOVPAY_FULLVERSION}/dist/cfg/* ${GOVPAY_HOME}/


ARG govpay_as_custom_scripts=commons/entrypoint.sh
COPY ${govpay_as_custom_scripts}* /var/tmp/custom_cli
RUN [ -d /var/tmp/custom_cli ] && cp -r /var/tmp/custom_cli/ ${CATALINA_HOME}/conf || echo "Personalizzazioni per AS non presenti"


COPY commons/entrypoint.sh commons/initgovpay.sh commons/config_datasource.sh commons/tomcat-cli.sh /usr/local/bin/

# Hook di avvio: esternalizzazione Config.js console GovPay (vedi console/README.md)
COPY --chown=tomcat:0 commons/console-static-config.sh /docker-entrypoint-govpay.d/30-console-static-config.sh

ARG oracle_custom_jdbc=commons/entrypoint.sh
COPY ${oracle_custom_jdbc}* /var/tmp/oracle_custom_jdbc
RUN [ -d /var/tmp/oracle_custom_jdbc ] || echo "Driver jdbc Oracle non presente"

RUN  sed -i -e 's/<!--.*-->//g' -e '/<!--/,/-->/d'  ${CATALINA_HOME}/conf/server.xml ${CATALINA_HOME}/conf/context.xml; \
sed -i -e  "s#\${catalina.base}/logs#${GOVPAY_LOGDIR}#" ${CATALINA_HOME}/conf/logging.properties; \
echo -e '# Rimuovi Resource UserDatabase \n\
/Server/GlobalNamingResources/Resource[@name="UserDatabase"]:delete\n\
# Rimuovi Realm UserDatabase\n\
/Server/Service/Engine/Realm/Realm[@resourceName="UserDatabase"]:delete\n\
# Aggiungi Executor http-worker\n\
/Server/Service/Executor:top name=http-worker, namePrefix=http-worker-, maxThreads=${GOVPAY_AS_HTTP_WORKER_MAX_THREADS:-100}\n\
# Aggiungi Executor https-worker\n\
/Server/Service/Executor:top name=https-worker, namePrefix=https-worker-, maxThreads=${GOVPAY_AS_HTTPS_WORKER_MAX_THREADS:-100}\n\
# Aggiungi Executor https-mtls-worker\n\
/Server/Service/Executor:top name=https-mtls-worker, namePrefix=https-mtls-worker-, maxThreads=${GOVPAY_AS_HTTPS_MTLS_WORKER_MAX_THREADS:-20}, minSpareThreads=5\n\
# Aggiungi Executor ajp-worker\n\
/Server/Service/Executor:top name=ajp-worker, namePrefix=ajp-worker-, maxThreads=${GOVPAY_AS_AJP_WORKER_MAX_THREADS:-50}\n\
# Rimuovi connettore HTTPS su porta 8443\n\
/Server/Service/Connector[@port="8443"]:delete\n\
# Rimuovi connettore HTTP su porta 8080\n\
/Server/Service/Connector[@port="8080"]:delete\n\
# Aggiungi connettore HTTP su porta 8080\n\
/Server/Service/Connector:add port=8080, protocol=HTTP/1.1, connectionTimeout=20000, redirectPort=8443, executor=http-worker, maxHttpHeaderSize=${GOVPAY_AS_MAX_HTTP_SIZE:-1048576}, maxPostSize=${GOVPAY_AS_MAX_POST_SIZE:-10485760}, bindOnInit=false\n\
# Aggiungi connettore HTTPS\n\
/Server/Service/Connector:add port=8443, protocol=HTTP/1.1, SSLEnabled=true, executor=https-worker, maxPostSize=${GOVPAY_AS_MAX_POST_SIZE:-10485760}, bindOnInit=false\n\
/Server/Service/Connector[@executor="https-worker"]/SSLHostConfig:add protocols=TLSv1.2\n\
/Server/Service/Connector[@executor="https-worker"]/SSLHostConfig/Certificate:add protocols=TLSv1.2, certificateKeystoreFile=${GOVPAY_AS_KEYSTORE}, certificateKeystorePassword=${GOVPAY_AS_KEYSTORE_PASSWORD}, certificateKeystoreType=${GOVPAY_AS_KEYSTORE_TIPO:-jks}, certificateKeyPassword=${GOVPAY_AS_KEYSTORE_KEY_PASSWORD}\n\
# Aggiungi connettore HTTPS con MTLS\n\
/Server/Service/Connector:add port=8445, protocol=HTTP/1.1, SSLEnabled=true, executor=https-mtls-worker, maxPostSize=${GOVPAY_AS_MAX_POST_SIZE:-10485760}, bindOnInit=false\n\
/Server/Service/Connector[@executor="https-mtls-worker"]/SSLHostConfig:add protocols=TLSv1.2, truststoreFile=${GOVPAY_AS_TRUSTSTORE}, truststorePassword=${GOVPAY_AS_TRUSTSTORE_PASSWORD}, truststoreType=${GOVPAY_AS_TRUSTSTORE_TIPO:-jks}, certificateVerification=required\n\
/Server/Service/Connector[@executor="https-mtls-worker"]/SSLHostConfig[@certificateVerification="required"]/Certificate:add certificateKeystoreFile=${GOVPAY_AS_KEYSTORE}, certificateKeystorePassword=${GOVPAY_AS_KEYSTORE_PASSWORD}, certificateKeystoreType=${GOVPAY_AS_KEYSTORE_TIPO:-jks}, certificateKeyPassword=${GOVPAY_AS_KEYSTORE_KEY_PASSWORD}\n\
# Aggiungi connettore AJP su porta 8009\n\
/Server/Service/Connector:add port=8009, protocol=AJP/1.3, redirectPort=8443, executor=ajp-worker, maxPostSize=${GOVPAY_AS_MAX_POST_SIZE:-10485760}, secretRequired=${GOVPAY_AS_AJP_SECRET:-false}\n\
# Aggiungi gestione del suspend timeout\n\
/Server/Service:write-attribute gracefulStopAwaitMillis=${GOVPAY_SUSPEND_TIMEOUT:-20}\n\
# Configura RemoteIpValve\n\
/Server/Service/Engine/Host/Valve:add className=org.apache.catalina.valves.RemoteIpValve, remoteIpHeader=x-forwarded-for, proxiesHeader=x-forwarded-by, protocolHeader=x-forwarded-proto\n\
# Configura RewriteValve\n\
/Server/Service/Engine/Host/Valve:add className=org.apache.catalina.valves.rewrite.RewriteValve\n\
# Configura AccessLogValve\n\
/Server/Service/Engine/Host/Valve[@className="org.apache.catalina.valves.AccessLogValve"]:write-attribute directory=${GOVPAY_LOGDIR}, suffix=.log \n\
' > /tmp/tomcat_configuration.cli; \ 
chmod 750 /usr/local/bin/tomcat-cli.sh /usr/local/bin/config_datasource.sh ; \
/usr/local/bin/config_datasource.sh /tmp/tomcat_configuration.cli; \
/usr/local/bin/tomcat-cli.sh /tmp/tomcat_configuration.cli; \
echo "org.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource" >> "${CATALINA_HOME}/conf/catalina.properties"; \
rm -rf /tmp/*; 


RUN mkdir -p /opt/hsqldb-${HSQLDB_FULLVERSION}/hsqldb/database/ /usr/share/licenses/govpay/third-party-licenses \
&& chown -R tomcat:0 /usr/local/bin/entrypoint.sh /usr/local/bin/initgovpay.sh /usr/local/bin/tomcat-cli.sh ${CATALINA_HOME} ${GOVPAY_HOME} ${GOVPAY_HOME_HTTPS} ${GOVPAY_LOGDIR} /opt/hsqldb-${HSQLDB_FULLVERSION}/hsqldb/database/ \
&& chmod -Rf g+rwX  ${CATALINA_HOME} ${GOVPAY_HOME} ${GOVPAY_HOME_HTTPS} ${GOVPAY_LOGDIR} /opt/hsqldb-${HSQLDB_FULLVERSION}/hsqldb/database/ /opt/${GOVPAY_DB_TYPE}/ \
&& chmod ug=rx /usr/local/bin/entrypoint.sh /usr/local/bin/initgovpay.sh /usr/local/bin/tomcat-cli.sh /docker-entrypoint-govpay.d/30-console-static-config.sh \
&& chmod u+s /usr/local/bin/change_dir_perms 

COPY --from=source_image_full /opt/govpay-installer-${GOVPAY_FULLVERSION}/doc/README.txt \
/opt/govpay-installer-${GOVPAY_FULLVERSION}/doc/LICENSE* \
/opt/govpay-installer-${GOVPAY_FULLVERSION}/doc/COPYING* \
/usr/share/licenses/govpay/
COPY --from=source_image_full /opt/govpay-installer-${GOVPAY_FULLVERSION}/doc/README.txt /opt/govpay-installer-${GOVPAY_FULLVERSION}/doc/third-party-licenses* /usr/share/licenses/govpay/third-party-licenses/
USER tomcat
WORKDIR /usr/local/tomcat
EXPOSE 8080 8443 8445 8009
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]
CMD []
