openapi: 3.0.0
info:
  version: "3.0.0"
  title: GovPay - API Ragioneria
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - url: /govpay/backend/api/ragioneria/rs/basic/v3/
tags:
  - name: Rendicontazioni
  - name: Ricevute
  - name: Riconciliazioni
  - name: Riscossioni
  - name: Utenti
    description: Anagrafica degli Utenti
security:
  - basicAuth: []    
paths:
  '/flussiRendicontazione':
    get:
      summary: Elenco dei flussi di rendicontazione acquisite da pagoPa
      operationId: findFlussiRendicontazione
      tags:
        - Rendicontazioni
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/pagina'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/risultatiPerPagina'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/ordinamento'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/idDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/dataDa'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/dataA'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/statoFlussoRendicontazione'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/metadatiPaginazione'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/maxRisultati'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/iuv'
      responses:
        '200':
          description: Lista dei flussi rendicontazione
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/FlussiRendicontazione'
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'                
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'  
  '/flussiRendicontazione/{idFlusso}':
    get:
      summary: Acquisizione di un flusso di rendicontazione
      operationId: getFlussoRendicontazione
      tags:
        - Rendicontazioni
      parameters:
        - in: path
          name: idFlusso
          description: Identificativo del flusso di rendicontazione
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dettaglio della rendicontazione
          content:
            application/xml:
              schema:
                type: string
                example: xml del flusso di rendicontazione
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/FlussoRendicontazione'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '404':
          $ref: 'govpay-api-responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'  
  '/flussiRendicontazione/{idFlusso}/{dataOraFlusso}':
    get:
      summary: Acquisizione di un flusso di rendicontazione
      operationId: getFlussoRendicontazioneByIdEData
      tags:
        - Rendicontazioni
      parameters:
        - in: path
          name: idFlusso
          description: Identificativo del flusso di rendicontazione
          required: true
          schema:
            type: string
        - in: path
          name: dataOraFlusso
          description: Data di emissione del flusso
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '201':
          description: Dettaglio della rendicontazione
          content:
            application/xml:
              schema:
                type: string
                example: xml del flusso di rendicontazione
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/FlussoRendicontazione'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '404':
          $ref: 'govpay-api-responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'
  '/ricevute':
    get:
      operationId: findRicevute
      summary: Ricerca delle ricevute di pagamento
      tags:
        - Ricevute
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/pagina'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/risultatiPerPagina'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/ordinamento'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/idDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/dataDa'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/dataA'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/metadatiPaginazione'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/maxRisultati'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/iuv'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/idRicevuta'
      responses:
        '200':
          description: Lista dei flussi rendicontazione
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/FlussiRendicontazione'
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'                
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'        
  '/ricevute/{idDominio}/{iuv}/{idRicevuta}':
    get:
      operationId: getRicevuta
      summary: Acquisizione di una ricevuta di avvenuto pagamento pagoPA
      description: >-
        Ricevuta pagoPA, sia questa veicolata nella forma di `RT` o di `recepit`, di esito positivo. 
      tags:
        - Ricevute
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIuv'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdRicevuta'
      responses:
        '201':
          description: ricevuta di pagamento acquisita
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/Ricevuta'
              examples:
                Pagamento standard: 
                  $ref: 'govpay-api-examples.yaml#/components/examples/RicevutaEntrata'
                Marca da bollo: 
                  $ref: 'govpay-api-examples.yaml#/components/examples/RicevutaMBT'              
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'             
  '/riconciliazioni':
    get:
      summary: Elenco dei movimenti di cassa riconciliati
      operationId: findRiconciliazioni
      tags:
        - Riconciliazioni
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/pagina'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/risultatiPerPagina'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/idDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/dataDa'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/dataA'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/metadatiPaginazione'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/maxRisultati'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/sct'
      responses:
        '200':
          description: Dettaglio dell'incasso
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/Riconciliazioni'
              example:
                numRisultati: 2
                numPagine: 1
                risultatiPerPagina: 25
                pagina: 1
                risultati:
                  - id: '12345'
                    dominio: 
                      idDominio: 01234567890
                      ragioneSociale: "Comune Dimostrativo"
                    importo: 10
                    data: '2020-12-31'
                    dataValuta: '2020-12-31'
                    dataContabile: '2020-12-31'
                    contoAccredito: IT60X0542811101000000123456
                    sct: 2017-01-01ABI00000011234
                    trn: 2017-01-01ABI00000011234
                    iuv: RF23567483937849450550875
                  - id: '12346'
                    dominio: 
                      idDominio: 01234567890
                      ragioneSociale: "Comune Dimostrativo"
                    importo: 100.01
                    data: '2020-12-31'
                    dataValuta: '2020-12-31'
                    dataContabile: '2020-12-31'
                    contoAccredito: IT60X0542811101000000123456
                    idFlussoRendicontazione: '2020-11-21GovPAYPsp-1234567890'
                    causale: '000000000000000,00000000000000101,01EUR000000000000000,000000000000000000000000,000000000000,00/ZZ2SATISPAY EUROPE SA/ZZ3Comune Dimostrativo/PUR/LGPE-RIVERSAMENTO/URI/2020-11-21GovPAYPsp-1234567890/ZZ4/4184/ZZ4/ID1357a8662b2256347456532f53f9a9825357a8662b2b911eb8da402f53f9a9825'
                
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'        
  '/riconciliazioni/{idDominio}/{id}':
    parameters:
      - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdDominio'
      - in: path
        name: id
        description: Identificativo dell'operazione di riconciliazione
        required: true
        schema:
          type: string  
          pattern: '(^([0-9A-Za-z]){1,35}$)'
    put:
      summary: Riconciliazione di un movimento di cassa
      operationId: addRiconciliazione
      tags:
        - Riconciliazioni
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NuovaRiconciliazione'
            example:
              importo: 100.01
              dataValuta: '2020-12-31'
              dataContabile: '2020-12-31'
              contoAccredito: IT60X0542811101000000123456
              sct: 00000011234
              causale: '000000000000000,00000000000000101,01EUR000000000000000,000000000000000000000000,000000000000,00/ZZ2SATISPAY EUROPE SA/ZZ3Comune Dimostrativo/PUR/LGPE-RIVERSAMENTO/URI/2020-11-21GovPAYPsp-1234567890/ZZ4/4184/ZZ4/ID1357a8662b2256347456532f53f9a9825357a8662b2b911eb8da402f53f9a9825'
      responses:
        '200':
          description: Riconciliazione
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/Riconciliazione'          
        '202':
          $ref: 'govpay-api-responses.yaml#/components/responses/202Accepted'          
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'          
    get:
      summary: Dettaglio di un movimento di cassa riconciliato
      operationId: getRiconciliazione
      tags:
        - Riconciliazioni
      responses:
        '200':
          description: Riconciliazione
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/Riconciliazione'  
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '404':
          $ref: 'govpay-api-responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'    
  '/riscossioni':
    get:
      summary: Elenco degli importi riscossi o stornati
      operationId: findRiscossioni
      tags:
        - Riscossioni
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/pagina'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/risultatiPerPagina'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/campi'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/ordinamento'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/idDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/dataDa'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/dataA'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/statoRiscossione'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/tipiRiscossione'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/metadatiPaginazione'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/maxRisultati'
      responses:
        '200':
          description: Dettaglio della riscossione
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/Riscossioni'
        '400':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'                  
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'           
  '/riscossioni/{idDominio}/{iuv}/{iur}/{indice}':
    get:
      summary: Dettaglio di una riscossione
      operationId: getRiscossione
      tags:
        - Riscossioni
      parameters:
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIdDominio'
        - $ref: 'govpay-api-parameters.yaml#/components/parameters/PathIuv'
        - in: path
          name: iur
          description: Identificativo univoco di riscossione
          required: true
          schema:
            type: string
        - in: path
          name: indice
          description: Identificativo univoco di riscossione
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 5
      responses:
        '200':
          description: Dettaglio della riscossione
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/Riscossione'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '403':
          $ref: 'govpay-api-responses.yaml#/components/responses/403NotAuthorized'
        '404':
          $ref: 'govpay-api-responses.yaml#/components/responses/400BadRequest'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'                      
  '/profilo':
    get:
      summary: Elenco delle acl associate all'utenza chiamante
      tags:
        - Utenti
      operationId: getProfilo
      responses:
        '200':
          description: Autorizzazioni dell'utenza chiamante
          content:
            application/json:
              schema:
                $ref: 'govpay-api-schemas.yaml#/components/schemas/Profilo'
        '401':
          $ref: 'govpay-api-responses.yaml#/components/responses/401NotAuthenticated'
        '500':
          $ref: 'govpay-api-responses.yaml#/components/responses/500ServiceUnavailable'      
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    NuovaRiconciliazione:
      allOf:
        - $ref: '#/components/schemas/TipoRiferimentoNuovaRiconciliazione'
        - type: object
          required:
          - importo
          - sct
          properties:
            importo:
              type: number
              example: 100.01
              description: Importo del riversamento. Se valorizzato, viene verificato che corrisponda a quello dei pagamenti riconciliati.
            dataValuta:
              type: string
              format: date
              description: Data di valuta dell'incasso
              example: '2020-12-31'
            dataContabile:
              type: string
              format: date
              description: Data di contabile dell'incasso
              example: '2020-12-31'
            contoAccredito:
              type: string
              description: Identificativo del conto di tesoreria su cui sono stati incassati i fondi
              example: IT60X0542811101000000123456
            sct:
              type: string
              description: Identificativo Sepa Credit Transfer
              example: 2017-01-01ABI00000011234
    RiferimentoCausale:
      description: Causale dell'operazione di riversamento dal PSP alla Banca Tesoriera.
      type: object
      required:
        - causale
      properties:
        causale:
          type: string
          example: /PUR/LGPE-RIVERSAMENTO/URI/2017-01-01ABI00000011234  
    TipoRiferimentoNuovaRiconciliazione:
      type: object              
      oneOf:
        - $ref: '#/components/schemas/RiferimentoCausale'
        - $ref: '#/components/schemas/RiferimentoIdentificativoUnivocoVersamento'
        - $ref: '#/components/schemas/RiferimentoIdentificativoFlussoRendicontazione'
