<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="paForNode"
	targetNamespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/">
	<wsdl:types>
		<xsd:schema version="2.0.0"
			xmlns:imp="http://pagopa-api.pagopa.gov.it/paForNode/xsd/v2.0.0/">
			<xsd:import schemaLocation="paForNode_2_0_0.xsd"
				namespace="http://pagopa-api.pagopa.gov.it/paForNode/xsd/v2.0.0/"></xsd:import>

			<xsd:element name="paDemandPaymentNoticeRequest"
				type="imp:paDemandPaymentNoticeRequest" />
			<xsd:element name="paDemandPaymentNoticeResponse"
				type="imp:paDemandPaymentNoticeResponse" />

			<xsd:element name="paVeriFyPaymentNoticeRequest"
				type="imp:paVerifyPaymentNoticeRequest" />
			<xsd:element name="paVeriFyPaymentNoticeResponse"
				type="imp:paVerifyPaymentNoticeResponse" />

			<xsd:element name="paGetPaymentRequest"
				type="imp:paGetPaymentRequest" />
			<xsd:element name="paGetPaymentResponse"
				type="imp:paGetPaymentResponse" />

			<xsd:element name="paSendRTRequest"
				type="imp:paSendRTRequest" />
			<xsd:element name="paSendRTResponse"
				type="imp:paSendRTResponse" />

		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="paDemandPaymentNotice">
		<wsdl:part name="bodyrequest"
			element="paDemandPaymentNoticeRequest">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="paDemandPaymentNoticeResponse">
		<wsdl:part name="bodyresponse"
			element="paDemandPaymentNoticeResponse"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="paVeriFyPaymentNotice">
		<wsdl:part name="bodyrequest"
			element="paVeriFyPaymentNoticeRequest"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="paVeriFyPaymentNoticeResponse">
		<wsdl:part name="bodyresponse"
			element="paVeriFyPaymentNoticeResponse"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="paGetPayment">
		<wsdl:part name="bodyrequest" element="paGetPaymentRequest"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="paGetPaymentResponse">
		<wsdl:part name="bodyresponse"
			element="paGetPaymentResponse"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="paSendRT">
		<wsdl:part name="bodyrequest" element="paSendRTRequest"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="paSendRTResponse">
		<wsdl:part name="bodyresponse" element="paSendRTResponse"></wsdl:part>
	</wsdl:message>
	<wsdl:portType name="paForNode">
		<wsdl:operation name="paDemandPaymentNotice">
			<wsdl:input message="tns:paDemandPaymentNotice"></wsdl:input>
			<wsdl:output message="tns:paDemandPaymentNoticeResponse"></wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="paVeriFyPaymentNotice">
			<wsdl:input message="tns:paVeriFyPaymentNotice"></wsdl:input>
			<wsdl:output message="tns:paVeriFyPaymentNoticeResponse"></wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="paGetPayment">
			<wsdl:input message="tns:paGetPayment"></wsdl:input>
			<wsdl:output message="tns:paGetPaymentResponse"></wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="paSendRT">
			<wsdl:input message="tns:paSendRT"></wsdl:input>
			<wsdl:output message="tns:paSendRTResponse"></wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="paForNodeBinding" type="tns:paForNode">
		<soap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="paDemandPaymentNotice">
			<soap:operation
				soapAction="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/paDemandPaymentNotice" />
			<wsdl:input>
				<soap:body use="literal"
					namespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"
					namespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="paVeriFyPaymentNotice">
			<soap:operation
				soapAction="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/paVeriFyPaymentNotice" />
			<wsdl:input>
				<soap:body use="literal"
					namespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"
					namespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="paGetPayment">
			<soap:operation
				soapAction="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/paGetPayment" />
			<wsdl:input>
				<soap:body use="literal"
					namespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"
					namespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="paSendRT">
			<soap:operation
				soapAction="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/paSendRT" />
			<wsdl:input>
				<soap:body use="literal"
					namespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"
					namespace="http://pagopa-api.pagopa.gov.it/paForNode/v2.0.0/" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="paForNodeService">
		<wsdl:port name="paForNodePort"
			binding="tns:paForNodeBinding">
			<soap:address location="http://pagopa-api.pagopa.gov.it/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>