/*
 * GovPay - Porta di Accesso al Nodo dei Pagamenti SPC 
 * http://www.gov4j.it/govpay
 * 
 * Copyright (c) 2014-2015 Link.it srl (http://www.link.it).
 * Copyright (c) 2014-2015 TAS S.p.A. (http://www.tasgroup.it).
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package it.govpay.ejb.ndp.pojo;

public enum NdpFaultCode {

	PPT_SINTASSI_XSD,
	PPT_SINTASSI_EXTRAXSD,
	PPT_SEMANTICA,
	PPT_AUTENTICAZIONE,
	PPT_AUTORIZZAZIONE,
	PPT_DOMINIO_SCONOSCIUTO,
	PPT_DOMINIO_DISABILITATO,
	PPT_STAZIONE_INT_PA_SCONOSCIUTA,
	PPT_STAZIONE_INT_PA_DISABILITATA,
	PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE,
	PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO,
	PPT_CANALE_SCONOSCIUTO,
	PPT_CANALE_IRRAGGIUNGIBILE,
	PPT_CANALE_SERVIZIO_NONATTIVO,
	PPT_CANALE_TIMEOUT,
	PPT_CANALE_DISABILITATO,
	PPT_CANALE_NONRISOLVIBILE,
	PPT_CANALE_INDISPONIBILE,
	PPT_CANALE_ERRORE,
	PPT_CANALE_ERR_PARAM_PAG_IMM,
	PPT_CANALE_ERRORE_RESPONSE,
	PPT_PSP_SCONOSCIUTO,
	PPT_PSP_DISABILITATO,
	PPT_RPT_DUPLICATA,
	PPT_RPT_SCONOSCIUTA,
	PPT_RT_SCONOSCIUTA,
	PPT_RT_NONDISPONIBILE,
	PPT_SUPERAMENTOSOGLIA,
	PPT_TIPOFIRMA_SCONOSCIUTO,
	PPT_ERRORE_FORMATO_BUSTA_FIRMATA,
	PPT_FIRMA_INDISPONIBILE,
	PPT_CODIFICA_PSP_SCONOSCIUTA,
	PPT_ID_FLUSSO_SCONOSCIUTO,
	PPT_ERRORE_EMESSO_DA_PAA,
	PPT_SYSTEM_ERROR,
	PAA_ID_DOMINIO_ERRATO,
	PAA_ID_INTERMEDIARIO_ERRATO,
	PAA_STAZIONE_INT_ERRATA,
	PAA_RPT_SCONOSCIUTA,
	PAA_RT_DUPLICATA,
	PAA_TIPOFIRMA_SCONOSCIUTO,
	PAA_ERRORE_FORMATO_BUSTA_FIRMATA,
	PAA_FIRMA_ERRATA,
	PAA_FIRMA_INDISPONIBILE,
	PAA_PAGAMENTO_SCONOSCIUTO,
	PAA_PAGAMENTO_DUPLICATO,
	PAA_PAGAMENTO_IN_CORSO,
	PAA_PAGAMENTO_ANNULLATO,
	PAA_PAGAMENTO_SCADUTO,
	PAA_SINTASSI_XSD,
	PAA_SINTASSI_EXTRAXSD,
	PAA_SEMANTICA,
	CANALE_SINTASSI_XSD,
	CANALE_SINTASSI_EXTRAXSD,
	CANALE_SEMANTICA,
	CANALE_RPT_DUPLICATA,
	CANALE_RPT_SCONOSCIUTA,
	CANALE_RPT_RIFIUTATA,
	CANALE_RT_SCONOSCIUTA,
	CANALE_RT_NON_DISPONIBILE,
	CANALE_INDISPONIBILE,
	CANALE_RICHIEDENTE_ERRATO,
	CANALE_SYSTEM_ERROR,
	PAA_ER_DUPLICATA,
	PAA_ERRORE_INTERNO;

}
