//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package it.gov.digitpa.schemas._2011.psp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctErogazioneServizio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctErogazioneServizio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="disponibilita" type="{}ctErogazione" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="indisponibilita" type="{}ctErogazione" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctErogazioneServizio", propOrder = {
    "disponibilitas",
    "indisponibilitas"
})
public class CtErogazioneServizio {

    @XmlElement(name = "disponibilita")
    protected List<CtErogazione> disponibilitas;
    @XmlElement(name = "indisponibilita")
    protected List<CtErogazione> indisponibilitas;

    /**
     * Gets the value of the disponibilitas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disponibilitas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisponibilitas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtErogazione }
     * 
     * 
     */
    public List<CtErogazione> getDisponibilitas() {
        if (disponibilitas == null) {
            disponibilitas = new ArrayList<CtErogazione>();
        }
        return this.disponibilitas;
    }

    /**
     * Gets the value of the indisponibilitas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the indisponibilitas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndisponibilitas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtErogazione }
     * 
     * 
     */
    public List<CtErogazione> getIndisponibilitas() {
        if (indisponibilitas == null) {
            indisponibilitas = new ArrayList<CtErogazione>();
        }
        return this.indisponibilitas;
    }

}
