//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package it.gov.digitpa.schemas._2011.psp;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import it.govpay.core.utils.adapter.TimeAdapter;


/**
 * <p>Java class for ctFasciaOraria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctFasciaOraria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fasciaOrariaDa" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="fasciaOrariaA" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctFasciaOraria", propOrder = {
    "fasciaOrariaDa",
    "fasciaOrariaA"
})
public class CtFasciaOraria {

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(TimeAdapter.class)
    @XmlSchemaType(name = "time")
    protected Date fasciaOrariaDa;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(TimeAdapter.class)
    @XmlSchemaType(name = "time")
    protected Date fasciaOrariaA;

    /**
     * Gets the value of the fasciaOrariaDa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFasciaOrariaDa() {
        return this.fasciaOrariaDa;
    }

    /**
     * Sets the value of the fasciaOrariaDa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFasciaOrariaDa(Date value) {
        this.fasciaOrariaDa = value;
    }

    /**
     * Gets the value of the fasciaOrariaA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFasciaOrariaA() {
        return this.fasciaOrariaA;
    }

    /**
     * Sets the value of the fasciaOrariaA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFasciaOrariaA(Date value) {
        this.fasciaOrariaA = value;
    }

}
