//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package it.gov.digitpa.schemas._2011.psp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctIdentificazioneServizio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctIdentificazioneServizio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nomeServizio" type="{}stText35"/>
 *         &lt;element name="logoServizio" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctIdentificazioneServizio", propOrder = {
    "nomeServizio",
    "logoServizio"
})
public class CtIdentificazioneServizio {

    @XmlElement(required = true)
    protected String nomeServizio;
    @XmlElement(required = true)
    protected byte[] logoServizio;

    /**
     * Gets the value of the nomeServizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeServizio() {
        return nomeServizio;
    }

    /**
     * Sets the value of the nomeServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeServizio(String value) {
        this.nomeServizio = value;
    }

    /**
     * Gets the value of the logoServizio property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLogoServizio() {
        return logoServizio;
    }

    /**
     * Sets the value of the logoServizio property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLogoServizio(byte[] value) {
        this.logoServizio = ((byte[]) value);
    }

}
