//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package it.gov.digitpa.schemas._2011.psp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctInformativaDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctInformativaDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identificativoIntermediario" type="{}stText35"/>
 *         &lt;element name="identificativoCanale" type="{}stText35"/>
 *         &lt;element name="tipoVersamento" type="{}stTipoVersamento"/>
 *         &lt;element name="modelloPagamento" type="{}stModelloPagamento"/>
 *         &lt;element name="priorita" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="canaleApp" type="{}stZeroUno"/>
 *         &lt;element name="generazioneEsitoTransazione" type="{}stZeroUno" minOccurs="0"/>
 *         &lt;element name="servizioAlleImprese" type="{}stZeroUno" minOccurs="0"/>
 *         &lt;element name="pagamentiPreEsercizio" type="{}stZeroUno" minOccurs="0"/>
 *         &lt;element name="identificazioneServizio" type="{}ctIdentificazioneServizio" minOccurs="0"/>
 *         &lt;element name="listaInformazioniServizio" type="{}ctListaInformazioniServizio"/>
 *         &lt;element name="listaParoleChiave" type="{}ctListaParoleChiave" minOccurs="0"/>
 *         &lt;element name="costiServizio" type="{}ctCostiServizio"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctInformativaDetail", propOrder = {
    "identificativoIntermediario",
    "identificativoCanale",
    "tipoVersamento",
    "modelloPagamento",
    "priorita",
    "canaleApp",
    "generazioneEsitoTransazione",
    "servizioAlleImprese",
    "pagamentiPreEsercizio",
    "identificazioneServizio",
    "listaInformazioniServizio",
    "listaParoleChiave",
    "costiServizio"
})
public class CtInformativaDetail {

    @XmlElement(required = true)
    protected String identificativoIntermediario;
    @XmlElement(required = true)
    protected String identificativoCanale;
    @XmlElement(required = true)
    protected StTipoVersamento tipoVersamento;
    protected int modelloPagamento;
    protected int priorita;
    protected int canaleApp;
    protected Integer generazioneEsitoTransazione;
    protected Integer servizioAlleImprese;
    protected Integer pagamentiPreEsercizio;
    protected CtIdentificazioneServizio identificazioneServizio;
    @XmlElement(required = true)
    protected CtListaInformazioniServizio listaInformazioniServizio;
    protected CtListaParoleChiave listaParoleChiave;
    @XmlElement(required = true)
    protected CtCostiServizio costiServizio;

    /**
     * Gets the value of the identificativoIntermediario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativoIntermediario() {
        return identificativoIntermediario;
    }

    /**
     * Sets the value of the identificativoIntermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativoIntermediario(String value) {
        this.identificativoIntermediario = value;
    }

    /**
     * Gets the value of the identificativoCanale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativoCanale() {
        return identificativoCanale;
    }

    /**
     * Sets the value of the identificativoCanale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativoCanale(String value) {
        this.identificativoCanale = value;
    }

    /**
     * Gets the value of the tipoVersamento property.
     * 
     * @return
     *     possible object is
     *     {@link StTipoVersamento }
     *     
     */
    public StTipoVersamento getTipoVersamento() {
        return tipoVersamento;
    }

    /**
     * Sets the value of the tipoVersamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link StTipoVersamento }
     *     
     */
    public void setTipoVersamento(StTipoVersamento value) {
        this.tipoVersamento = value;
    }

    /**
     * Gets the value of the modelloPagamento property.
     * 
     */
    public int getModelloPagamento() {
        return modelloPagamento;
    }

    /**
     * Sets the value of the modelloPagamento property.
     * 
     */
    public void setModelloPagamento(int value) {
        this.modelloPagamento = value;
    }

    /**
     * Gets the value of the priorita property.
     * 
     */
    public int getPriorita() {
        return priorita;
    }

    /**
     * Sets the value of the priorita property.
     * 
     */
    public void setPriorita(int value) {
        this.priorita = value;
    }

    /**
     * Gets the value of the canaleApp property.
     * 
     */
    public int getCanaleApp() {
        return canaleApp;
    }

    /**
     * Sets the value of the canaleApp property.
     * 
     */
    public void setCanaleApp(int value) {
        this.canaleApp = value;
    }

    /**
     * Gets the value of the generazioneEsitoTransazione property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGenerazioneEsitoTransazione() {
        return generazioneEsitoTransazione;
    }

    /**
     * Sets the value of the generazioneEsitoTransazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGenerazioneEsitoTransazione(Integer value) {
        this.generazioneEsitoTransazione = value;
    }

    /**
     * Gets the value of the servizioAlleImprese property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServizioAlleImprese() {
        return servizioAlleImprese;
    }

    /**
     * Sets the value of the servizioAlleImprese property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServizioAlleImprese(Integer value) {
        this.servizioAlleImprese = value;
    }

    /**
     * Gets the value of the pagamentiPreEsercizio property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPagamentiPreEsercizio() {
        return pagamentiPreEsercizio;
    }

    /**
     * Sets the value of the pagamentiPreEsercizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPagamentiPreEsercizio(Integer value) {
        this.pagamentiPreEsercizio = value;
    }

    /**
     * Gets the value of the identificazioneServizio property.
     * 
     * @return
     *     possible object is
     *     {@link CtIdentificazioneServizio }
     *     
     */
    public CtIdentificazioneServizio getIdentificazioneServizio() {
        return identificazioneServizio;
    }

    /**
     * Sets the value of the identificazioneServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtIdentificazioneServizio }
     *     
     */
    public void setIdentificazioneServizio(CtIdentificazioneServizio value) {
        this.identificazioneServizio = value;
    }

    /**
     * Gets the value of the listaInformazioniServizio property.
     * 
     * @return
     *     possible object is
     *     {@link CtListaInformazioniServizio }
     *     
     */
    public CtListaInformazioniServizio getListaInformazioniServizio() {
        return listaInformazioniServizio;
    }

    /**
     * Sets the value of the listaInformazioniServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtListaInformazioniServizio }
     *     
     */
    public void setListaInformazioniServizio(CtListaInformazioniServizio value) {
        this.listaInformazioniServizio = value;
    }

    /**
     * Gets the value of the listaParoleChiave property.
     * 
     * @return
     *     possible object is
     *     {@link CtListaParoleChiave }
     *     
     */
    public CtListaParoleChiave getListaParoleChiave() {
        return listaParoleChiave;
    }

    /**
     * Sets the value of the listaParoleChiave property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtListaParoleChiave }
     *     
     */
    public void setListaParoleChiave(CtListaParoleChiave value) {
        this.listaParoleChiave = value;
    }

    /**
     * Gets the value of the costiServizio property.
     * 
     * @return
     *     possible object is
     *     {@link CtCostiServizio }
     *     
     */
    public CtCostiServizio getCostiServizio() {
        return costiServizio;
    }

    /**
     * Sets the value of the costiServizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtCostiServizio }
     *     
     */
    public void setCostiServizio(CtCostiServizio value) {
        this.costiServizio = value;
    }

}
