//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package it.gov.digitpa.schemas._2011.psp;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import it.govpay.core.utils.adapter.DateTimeAdapter;


/**
 * <p>Java class for ctInformativaMaster complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctInformativaMaster">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataPubblicazione" type="{}stDateTimeGiornoOra"/>
 *         &lt;element name="dataInizioValidita" type="{}stDateTimeGiornoOra"/>
 *         &lt;element name="urlInformazioniPSP" type="{}stUrlInformazioni"/>
 *         &lt;element name="stornoPagamento" type="{}stZeroUno"/>
 *         &lt;element name="marcaBolloDigitale" type="{}stZeroUno"/>
 *         &lt;element name="logoPSP" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctInformativaMaster", propOrder = {
    "dataPubblicazione",
    "dataInizioValidita",
    "urlInformazioniPSP",
    "stornoPagamento",
    "marcaBolloDigitale",
    "logoPSP"
})
public class CtInformativaMaster {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    protected Date dataPubblicazione;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    protected Date dataInizioValidita;
    @XmlElement(required = true)
    protected String urlInformazioniPSP;
    protected int stornoPagamento;
    protected int marcaBolloDigitale;
    @XmlElement(required = true)
    protected byte[] logoPSP;

    /**
     * Gets the value of the dataPubblicazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDataPubblicazione() {
        return dataPubblicazione;
    }

    /**
     * Sets the value of the dataPubblicazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPubblicazione(Date value) {
        this.dataPubblicazione = value;
    }

    /**
     * Gets the value of the dataInizioValidita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * Sets the value of the dataInizioValidita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataInizioValidita(Date value) {
        this.dataInizioValidita = value;
    }

    /**
     * Gets the value of the urlInformazioniPSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlInformazioniPSP() {
        return urlInformazioniPSP;
    }

    /**
     * Sets the value of the urlInformazioniPSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlInformazioniPSP(String value) {
        this.urlInformazioniPSP = value;
    }

    /**
     * Gets the value of the stornoPagamento property.
     * 
     */
    public int getStornoPagamento() {
        return stornoPagamento;
    }

    /**
     * Sets the value of the stornoPagamento property.
     * 
     */
    public void setStornoPagamento(int value) {
        this.stornoPagamento = value;
    }

    /**
     * Gets the value of the marcaBolloDigitale property.
     * 
     */
    public int getMarcaBolloDigitale() {
        return marcaBolloDigitale;
    }

    /**
     * Sets the value of the marcaBolloDigitale property.
     * 
     */
    public void setMarcaBolloDigitale(int value) {
        this.marcaBolloDigitale = value;
    }

    /**
     * Gets the value of the logoPSP property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLogoPSP() {
        return logoPSP;
    }

    /**
     * Sets the value of the logoPSP property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLogoPSP(byte[] value) {
        this.logoPSP = ((byte[]) value);
    }

}
