//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package it.gov.digitpa.schemas._2011.psp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctServizioNonDiPagamento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctServizioNonDiPagamento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identificativoIntermediario" type="{}stText35"/>
 *         &lt;element name="identificativoCanale" type="{}stText35"/>
 *         &lt;element name="codiceServizioNonDiPagamento" type="{}stCodiceServizioNonDiPagamento"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctServizioNonDiPagamento", propOrder = {
    "identificativoIntermediario",
    "identificativoCanale",
    "codiceServizioNonDiPagamento"
})
public class CtServizioNonDiPagamento {

    @XmlElement(required = true)
    protected String identificativoIntermediario;
    @XmlElement(required = true)
    protected String identificativoCanale;
    protected int codiceServizioNonDiPagamento;

    /**
     * Gets the value of the identificativoIntermediario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativoIntermediario() {
        return this.identificativoIntermediario;
    }

    /**
     * Sets the value of the identificativoIntermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativoIntermediario(String value) {
        this.identificativoIntermediario = value;
    }

    /**
     * Gets the value of the identificativoCanale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativoCanale() {
        return this.identificativoCanale;
    }

    /**
     * Sets the value of the identificativoCanale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativoCanale(String value) {
        this.identificativoCanale = value;
    }

    /**
     * Gets the value of the codiceServizioNonDiPagamento property.
     * 
     */
    public int getCodiceServizioNonDiPagamento() {
        return this.codiceServizioNonDiPagamento;
    }

    /**
     * Sets the value of the codiceServizioNonDiPagamento property.
     * 
     */
    public void setCodiceServizioNonDiPagamento(int value) {
        this.codiceServizioNonDiPagamento = value;
    }

}
