//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 02:49:47 PM CEST 
//


package it.gov.digitpa.schemas._2011.psp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.gov.digitpa.schemas._2011.psp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.gov.digitpa.schemas._2011.psp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CtListaParoleChiave }
     * 
     */
    public CtListaParoleChiave createCtListaParoleChiave() {
        return new CtListaParoleChiave();
    }

    /**
     * Create an instance of {@link CtIdentificazioneServizio }
     * 
     */
    public CtIdentificazioneServizio createCtIdentificazioneServizio() {
        return new CtIdentificazioneServizio();
    }

    /**
     * Create an instance of {@link CtListaInformazioniServizio }
     * 
     */
    public CtListaInformazioniServizio createCtListaInformazioniServizio() {
        return new CtListaInformazioniServizio();
    }

    /**
     * Create an instance of {@link CtFasciaCostoServizio }
     * 
     */
    public CtFasciaCostoServizio createCtFasciaCostoServizio() {
        return new CtFasciaCostoServizio();
    }

    /**
     * Create an instance of {@link CtListaInformativaDetail }
     * 
     */
    public CtListaInformativaDetail createCtListaInformativaDetail() {
        return new CtListaInformativaDetail();
    }

    /**
     * Create an instance of {@link ListaInformativeControparte }
     * 
     */
    public ListaInformativeControparte createListaInformativeControparte() {
        return new ListaInformativeControparte();
    }

    /**
     * Create an instance of {@link CtInfoContoDiAccreditoPair }
     * 
     */
    public CtInfoContoDiAccreditoPair createCtInfoContoDiAccreditoPair() {
        return new CtInfoContoDiAccreditoPair();
    }

    /**
     * Create an instance of {@link CtServizioNonDiPagamento }
     * 
     */
    public CtServizioNonDiPagamento createCtServizioNonDiPagamento() {
        return new CtServizioNonDiPagamento();
    }

    /**
     * Create an instance of {@link CtListaServiziNonDiPagamento }
     * 
     */
    public CtListaServiziNonDiPagamento createCtListaServiziNonDiPagamento() {
        return new CtListaServiziNonDiPagamento();
    }

    /**
     * Create an instance of {@link CtInformazioniServizio }
     * 
     */
    public CtInformazioniServizio createCtInformazioniServizio() {
        return new CtInformazioniServizio();
    }

    /**
     * Create an instance of {@link CtCostiServizio }
     * 
     */
    public CtCostiServizio createCtCostiServizio() {
        return new CtCostiServizio();
    }

    /**
     * Create an instance of {@link ListaInformativePSP }
     * 
     */
    public ListaInformativePSP createListaInformativePSP() {
        return new ListaInformativePSP();
    }

    /**
     * Create an instance of {@link InformativaPSP }
     * 
     */
    public InformativaPSP createInformativaPSP() {
        return new InformativaPSP();
    }

    /**
     * Create an instance of {@link CtInformativaMaster }
     * 
     */
    public CtInformativaMaster createCtInformativaMaster() {
        return new CtInformativaMaster();
    }

    /**
     * Create an instance of {@link CtFasciaOraria }
     * 
     */
    public CtFasciaOraria createCtFasciaOraria() {
        return new CtFasciaOraria();
    }

    /**
     * Create an instance of {@link CtListaFasceCostoServizio }
     * 
     */
    public CtListaFasceCostoServizio createCtListaFasceCostoServizio() {
        return new CtListaFasceCostoServizio();
    }

    /**
     * Create an instance of {@link CtContiDiAccredito }
     * 
     */
    public CtContiDiAccredito createCtContiDiAccredito() {
        return new CtContiDiAccredito();
    }

    /**
     * Create an instance of {@link CtErogazioneServizio }
     * 
     */
    public CtErogazioneServizio createCtErogazioneServizio() {
        return new CtErogazioneServizio();
    }

    /**
     * Create an instance of {@link InformativaControparte }
     * 
     */
    public InformativaControparte createInformativaControparte() {
        return new InformativaControparte();
    }

    /**
     * Create an instance of {@link CtInformativaDetail }
     * 
     */
    public CtInformativaDetail createCtInformativaDetail() {
        return new CtInformativaDetail();
    }

    /**
     * Create an instance of {@link CtErogazione }
     * 
     */
    public CtErogazione createCtErogazione() {
        return new CtErogazione();
    }

    /**
     * Create an instance of {@link InformativaContoAccredito }
     * 
     */
    public InformativaContoAccredito createInformativaContoAccredito() {
        return new InformativaContoAccredito();
    }

}
