INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1110','2','1110','1110','Imposta regionale sulle attività produttive');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1120','2','1120','1120','Addizionale regionale all''imposta sul reddito delle persone fisiche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1130','2','1130','1130','Addizionale all''imposta di consumo sul gas metano');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1140','2','1140','1140','Tributo speciale per il deposito in discarica dei rifiuti solidi urbani');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1150','2','1150','1150','Imposte sulle concessioni statali dei beni del demanio e del patrimonio indisponibile');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1160','2','1160','1160','Imposta regionale sulla benzina per autotrazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1170','2','1170','1170','Altre imposte');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1210','2','1210','1210','Tasse automobilistiche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1220','2','1220','1220','Tassa regionale per il diritto allo studio universitario');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1230','2','1230','1230','Tassa sulle concessioni per la caccia e per la pesca');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1240','2','1240','1240','Altre tasse sulle concessioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1250','2','1250','1250','Tassa abilitazioni professionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1260','2','1260','1260','Altre tasse');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1310','2','1310','1310','Compartecipazione IVA');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1320','2','1320','1320','Quota regionale dell''accisa sulla benzina');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1330','2','1330','1330','Altre quote di tributi erariali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1401','2','1401','1401','IVA interna');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1402','2','1402','1402','IVA all''importazione e somma sostitutiva');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1403','2','1403','1403','Quota variabile del gettito Iva');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1404','2','1404','1404','Monopoli');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1405','2','1405','1405','Imposta di bollo');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1406','2','1406','1406','Imposta di registro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1407','2','1407','1407','Tasse di concessione governativa');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1408','2','1408','1408','Accisa sugli oli minerali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1409','2','1409','1409','Imposta erariale sull''energia elettrica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1410','2','1410','1410','Imposta di fabbricazione sugli spiriti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1411','2','1411','1411','IRPEF');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1412','2','1412','1412','IRPEG');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1413','2','1413','1413','Ritenute su redditi di capitali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1414','2','1414','1414','Imposte sul patrimonio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1415','2','1415','1415','Altre imposte');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_1416','2','1416','1416','IVA');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2111','2','2111','2111','Trasferimenti correnti da Stato per calamità naturali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2113','2','2113','2113','Trasferimenti correnti da Stato per Sanità');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2114','2','2114','2114','Trasferimenti correnti da Stato per concorso agli oneri di ammortamento di mutui');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2115','2','2115','2115','Trasferimenti da Stato per la realizzazione di programmi Comunitari');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2116','2','2116','2116','Altri trasferimenti correnti da Stato');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2117','2','2117','2117','Trasferimenti correnti da altri enti dell''Amministrazione centrale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2118','2','2118','2118','Trasferimenti correnti da Stato per Disavanzi sanitari pregressi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2119','2','2119','2119','Trasferimenti correnti da enti di ricerca dell''Amministrazione centrale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2120','2','2120','2120','Trasferimenti correnti da Enti di previdenza');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2131','2','2131','2131','Trasferimenti correnti da altre Regioni e Province autonome');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2132','2','2132','2132','Trasferimenti correnti da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2133','2','2133','2133','Trasferimenti correnti da Città metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2134','2','2134','2134','Trasferimenti correnti da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2135','2','2135','2135','Trasferimenti correnti da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2136','2','2136','2136','Trasferimenti correnti da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2137','2','2137','2137','Trasferimenti correnti da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2138','2','2138','2138','Trasferimenti correnti da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2139','2','2139','2139','Trasferimenti correnti da IRCCS pubblici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2140','2','2140','2140','Trasferimenti correnti da Enti di ricerca delle Amministrazioni locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2141','2','2141','2141','Trasferimenti correnti da Camere di commercio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2142','2','2142','2142','Trasferimenti correnti da Autorità portuali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2143','2','2143','2143','Trasferimenti correnti da Aziende di promozione turistica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2144','2','2144','2144','Trasferimenti correnti da Università');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2145','2','2145','2145','Trasferimenti correnti da Enti Parco Nazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2146','2','2146','2146','Trasferimenti correnti da ARPA');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2147','2','2147','2147','Trasferimenti correnti da Enti e agenzie regionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2148','2','2148','2148','Trasferimenti correnti da Organismi regionali interni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2149','2','2149','2149','Trasferimenti correnti da altri enti delle Amministrazioni locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2150','2','2150','2150','Trasferimenti correnti da Istituti Zooprofilattici Sperimentali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2151','2','2151','2151','Trasferimenti correnti da Policlinici Universitari');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2152','2','2152','2152','Trasferimenti correnti da Enti per il diritto allo studio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2153','2','2153','2153','Trasferimenti correnti da altre Regioni e Province autonome -Risorse UE');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2154','2','2154','2154','Trasferimenti correnti interni derivanti dalla contabilizzazione di economie di spesa');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2211','2','2211','2211','Trasferimenti correnti da Unione europea');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2212','2','2212','2212','Trasferimenti correnti da altre istituzioni estere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2213','2','2213','2213','Trasferimenti correnti da soggetti esteri privati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2313','2','2313','2313','Trasferimenti correnti da imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2314','2','2314','2314','Trasferimenti correnti da famiglie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2315','2','2315','2315','Trasferimenti correnti da istituzioni sociali private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_2316','2','2316','2316','Trasferimenti correnti da imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3111','2','3111','3111','Interessi attivi da Cassa Depositi e prestiti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3112','2','3112','3112','Interessi attivi da altri per finanziamenti a breve');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3113','2','3113','3113','Interessi attivi da altri per finanziamenti a medio-lungo');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3114','2','3114','3114','Interessi attivi da altri per anticipazioni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3115','2','3115','3115','Interessi attivi da altri per depositi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3116','2','3116','3116','Interessi attivi da altri da operazioni in derivati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3120','2','3120','3120','Utili netti delle aziende speciali e partecipate, dividendi di società');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3131','2','3131','3131','Canoni e fitti da Amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3132','2','3132','3132','Canoni e fitti da altri soggetti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3141','2','3141','3141','Altri redditi di capitale da Amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3142','2','3142','3142','Altri redditi di capitale da altri soggetti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3210','2','3210','3210','Proventi speciali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3220','2','3220','3220','Rimborsi per personale comandato');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3230','2','3230','3230','Altri recuperi e rimborsi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3231','2','3231','3231','Indennizzi di assicurazione');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3232','2','3232','3232','Fondi incentivanti il personale (legge Merloni)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_3240','2','3240','3240','Altre entrate correnti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4111','2','4111','4111','Alienazione di terreni e giacimenti');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4112','2','4112','4112','Alienazione di fabbricati residenziali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4113','2','4113','4113','Alienazione di fabbricati non residenziali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4114','2','4114','4114','Alienazione di altri beni immobili');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4115','2','4115','4115','Alienazione di beni mobili');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4116','2','4116','4116','Alienazione di macchine e attrezzature');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4117','2','4117','4117','Alienazione di beni immateriali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4122','2','4122','4122','Alienazione di partecipazioni in imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4123','2','4123','4123','Alienazione di titoli di Stato');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4124','2','4124','4124','Alienazione di altri titoli');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4125','2','4125','4125','Alienazione di partecipazioni in imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4211','2','4211','4211','Trasferimenti in conto capitale da Stato per calamità naturali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4212','2','4212','4212','Trasferimenti in conto capitale da Stato per Sanità');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4213','2','4213','4213','Trasferimenti in conto capitale da Stato per concorso agli oneri di ammortamento di mutui');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4214','2','4214','4214','Trasferimenti in conto capitale da Stato per la realizzazione di programmi Comunitari');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4215','2','4215','4215','Altri trasferimenti da Stato in conto capitale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4216','2','4216','4216','Trasferimenti in conto capitale da altri enti dell''Amministrazione centrale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4217','2','4217','4217','Trasferimenti in conto capitale da enti di ricerca dell''Amministrazione centrale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4220','2','4220','4220','Trasferimenti in conto capitale da Enti di previdenza');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4231','2','4231','4231','Trasferimenti in conto capitale da altre Regioni e Province autonome');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4232','2','4232','4232','Trasferimenti in conto capitale da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4233','2','4233','4233','Trasferimenti in conto capitale da Città metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4234','2','4234','4234','Trasferimenti in conto capitale da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4235','2','4235','4235','Trasferimenti in conto capitale da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4236','2','4236','4236','Trasferimenti in conto capitale da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4237','2','4237','4237','Trasferimenti in conto capitale da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4238','2','4238','4238','Trasferimenti in conto capitale da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4239','2','4239','4239','Trasferimenti in conto capitale da IRCCS pubblici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4240','2','4240','4240','Trasferimenti in conto capitale da Enti di ricerca delle Amministrazioni locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4241','2','4241','4241','Trasferimenti in conto capitale da Camere di commercio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4242','2','4242','4242','Trasferimenti in conto capitale da Autorità portuali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4243','2','4243','4243','Trasferimenti in conto capitale da Aziende di promozione turistica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4244','2','4244','4244','Trasferimenti in conto capitale da Università');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4245','2','4245','4245','Trasferimenti in conto capitale da Enti Parco Nazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4246','2','4246','4246','Trasferimenti in conto capitale da ARPA');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4247','2','4247','4247','Trasferimenti in conto capitale da Enti e agenzie regionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4248','2','4248','4248','Trasferimenti in conto capitale da Organismi regionali interni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4249','2','4249','4249','Trasferimenti in conto capitale da altri enti delle Amministrazioni locali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4250','2','4250','4250','Trasferimenti in conto capitale da Istituti Zooprofilattici Sperimentali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4251','2','4251','4251','Trasferimenti in conto capitale da Policlinici Universitari');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4252','2','4252','4252','Trasferimenti in conto capitale da Enti per il diritto allo studio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4253','2','4253','4253','Trasferimenti in conto capitale da altre Regioni e Province autonome -Risorse UE');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4254','2','4254','4254','Trasferimenti in c/capitale interni derivanti dalla contabilizzazione di economie di spesa');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4311','2','4311','4311','Trasferimenti in conto capitale da Unione europea');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4312','2','4312','4312','Trasferimenti in conto capitale da altre istituzioni estere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4313','2','4313','4313','Trasferimenti in conto capitale da soggetti esteri privati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4413','2','4413','4413','Trasferimenti in conto capitale da imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4414','2','4414','4414','Trasferimenti in conto capitale da famiglie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4415','2','4415','4415','Trasferimenti in conto capitale da istituzioni sociali private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4416','2','4416','4416','Trasferimenti in conto capitale da imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4501','2','4501','4501','Riscossioni di crediti da altre Regioni e Province autonome');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4502','2','4502','4502','Riscossioni di crediti da Province');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4503','2','4503','4503','Riscossioni di crediti da Città metropolitane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4504','2','4504','4504','Riscossioni di crediti da Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4505','2','4505','4505','Riscossioni di crediti da Unioni di Comuni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4506','2','4506','4506','Riscossioni di crediti da Comunità montane');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4507','2','4507','4507','Riscossioni di crediti da Aziende sanitarie');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4508','2','4508','4508','Riscossioni di crediti da Aziende ospedaliere');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4509','2','4509','4509','Riscossioni di crediti da IRCCS pubblici');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4510','2','4510','4510','Riscossioni di crediti da Enti di ricerca');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4511','2','4511','4511','Riscossioni di crediti da Camere di commercio');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4512','2','4512','4512','Riscossioni di crediti da Autorità portuali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4513','2','4513','4513','Riscossioni di crediti da Aziende di promozione turistica');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4514','2','4514','4514','Riscossioni di crediti da Università');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4515','2','4515','4515','Riscossioni di crediti da Enti Parco Nazionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4516','2','4516','4516','Riscossioni di crediti da ARPA');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4517','2','4517','4517','Riscossioni di crediti da Enti e agenzie regionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4518','2','4518','4518','Riscossioni di crediti da organismi regionali interni');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4519','2','4519','4519','Riscossioni di crediti da altri enti delle Amministrazioni pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4523','2','4523','4523','Riscossioni di crediti da imprese private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4524','2','4524','4524','Riscossioni di crediti da imprese pubbliche');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4530','2','4530','4530','Riscossioni di crediti da famiglie e Istituzioni Sociali private');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4540','2','4540','4540','Riscossioni di crediti da prelievi da depositi bancari');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_4550','2','4550','4550','Riscossioni di crediti da altri');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5111','2','5111','5111','Mutui da Cassa Depositi e prestiti gestione tesoro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5112','2','5112','5112','Mutui da Cassa Depositi e prestiti gestione CDP spa');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5211','2','5211','5211','Emissione di BOR in euro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5212','2','5212','5212','Emissione di BOR in altre valute');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5221','2','5221','5221','Emissione di altri titoli obbligazionari in euro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5222','2','5222','5222','Emissione di altri titoli obbligazionari in altre valute');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5301','2','5301','5301','Emissione di prestiti a medio e lungo termine da BEI');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5302','2','5302','5302','Emissione di altri prestiti a medio e lungo termine in euro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5303','2','5303','5303','Emissione di altri prestiti a medio e lungo termine in altre valute');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5411','2','5411','5411','Entrate derivanti da operazioni di cartolarizzazioni immobiliare (inferiori all''85% del valore del bene)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5412','2','5412','5412','Entrate derivanti da operazioni di cartolarizzazioni finanziaria (inferiori all''85% del valore del bene)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5511','2','5511','5511','Finanziamenti a breve termine in euro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5512','2','5512','5512','Finanziamenti a breve termine in altre valute');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_5610','2','5610','5610','ANTICIPAZIONI DI CASSA');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6111','2','6111','6111','Ritenute previdenziali e assistenziali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6112','2','6112','6112','Ritenute erariali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6113','2','6113','6113','Altre ritenute al personale per conto di terzi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6210','2','6210','6210','PRELEVAMENTI VERSAMENTI DAI CONTI CORRENTI DELLA TESORERIA STATALE');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6220','2','6220','6220','PRELEVAMENTI DAI CONTI DELLA GESTIONE SANITARIA');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6230','2','6230','6230','PRELEVAMENTI DAI CONTI DELLA GESTIONE ORDINARIA');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6311','2','6311','6311','Reintegro fondi economali e carte aziendali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6312','2','6312','6312','Depositi cauzionali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6313','2','6313','6313','Rimborso per spese per servizi per conto di terzi');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6314','2','6314','6314','Depositi per spese contrattuali');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6315','2','6315','6315','Sistema di Tesoreria regionale/provinciale');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6316','2','6316','6316','Reintegro ordini di accreditamento ai funzionari delegati');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6317','2','6317','6317','Anticipazioni sanità');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6318','2','6318','6318','Altre partite di giro');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_6319','2','6319','6319','Anticipazioni di tesoreria');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_9998','2','9998','9998','INCASSI DA REGOLARIZZARE DERIVANTI DALLE ANTICIPAZIONI DI CASSA (riscossioni codificate dal tesoriere)');
INSERT INTO tipi_tributo (cod_tributo, tipo_contabilita, cod_contabilita, cod_tributo_iuv, descrizione) VALUES ('SIOPE_R_9999','2','9999','9999','ALTRI INCASSI DA REGOLARIZZARE (riscossioni codificate dal tesoriere)');
