openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/govpay/backend/api/gde
  description: Generated server url
paths:
  /eventi:
    get:
      tags:
      - eventi
      summary: Ricerca eventi
      description: Ricerca eventi
      operationId: findEventi
      parameters:
      - name: pageable
        in: query
        description: informazioni di paginazione e ordinamento
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      - name: dataDa
        in: query
        description: Inizio della finestra temporale di osservazione
        required: false
        schema:
          type: string
          format: date-time
      - name: dataA
        in: query
        description: Fine della finestra temporale di osservazione
        required: false
        schema:
          type: string
          format: date-time
      - name: idDominio
        in: query
        description: Identificativo del dominio beneficiario
        required: false
        schema:
          type: string
      - name: iuv
        in: query
        description: Identificativo univoco di versamento
        required: false
        schema:
          type: string
      - name: ccp
        in: query
        description: Codice contesto pagamento/ID ricevuta
        required: false
        schema:
          type: string
      - name: idA2A
        in: query
        description: Identificativo del gestionale proprietario della pendenza
        required: false
        schema:
          type: string
      - name: idPendenza
        in: query
        description: Identificativo della pendenza nel gestionale proprietario
        required: false
        schema:
          type: string
      - name: idPagamento
        in: query
        description: Identificativo della richiesta di pagamento
        required: false
        schema:
          type: string
      - name: categoria
        in: query
        description: Filtro per categoria evento
        required: false
        schema:
          type: string
          enum:
          - INTERNO
          - INTERFACCIA
          - UTENTE
      - name: esito
        in: query
        description: Filtro per esito evento
        required: false
        schema:
          type: string
          enum:
          - OK
          - KO
          - FAIL
      - name: ruolo
        in: query
        description: Filtro per ruolo evento
        required: false
        schema:
          type: string
          enum:
          - CLIENT
          - SERVER
      - name: sottotipo
        in: query
        description: Filtro per sottotipo evento
        required: false
        schema:
          type: string
      - name: tipo
        in: query
        description: Filtro per tipo evento
        required: false
        schema:
          type: string
      - name: componente
        in: query
        description: Filtro per componente evento
        required: false
        schema:
          type: string
          enum:
          - API_BACKOFFICE
          - API_ENTE
          - API_PAGOPA
          - API_PAGAMENTO
          - API_PENDENZE
          - API_RAGIONERIA
          - API_BACKEND_IO
          - API_SECIM
          - API_MYPIVOT
          - API_MAGGIOLI_JPPA
          - API_GOVPAY
          - API_HYPERSIC_APK
          - API_USER
          - GOVPAY
      - name: severitaDa
        in: query
        description: Filtro per severita' errore
        required: false
        schema:
          type: integer
          format: int32
      - name: severitaA
        in: query
        description: Filtro per severita' errore
        required: false
        schema:
          type: integer
          format: int32
      responses:
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "200":
          description: Lista eventi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedModel'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
    post:
      tags:
      - eventi
      summary: Salvataggio di un nuovo evento
      description: Salvataggio di un nuovo evento
      operationId: addEvento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nuovoEvento'
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "201":
          description: Evento salvato con successo
          content:
            '*/*':
              schema:
                type: object
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
  /eventi/{id}:
    get:
      tags:
      - eventi
      summary: Dettaglio di un evento
      description: Dettaglio di un evento
      operationId: getEventoById
      parameters:
      - name: id
        in: path
        description: Id dell'evento da leggere.
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/problem'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        "200":
          description: Dettaglio Evento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/evento'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
components:
  schemas:
    problem:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
    Links:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Link'
    datiPagoPA:
      type: object
      properties:
        idPsp:
          type: string
        idCanale:
          type: string
        idIntermediarioPsp:
          type: string
        tipoVersamento:
          type: string
        modelloPagamento:
          type: string
        idDominio:
          type: string
        idIntermediario:
          type: string
        idStazione:
          type: string
        idRiconciliazione:
          type: string
        sct:
          type: string
        idFlusso:
          type: string
        idTracciato:
          type: number
        _links:
          $ref: '#/components/schemas/Links'
    nuovoEvento:
      type: object
      properties:
        id:
          type: integer
          format: int64
        componente:
          type: string
          enum:
          - API_BACKOFFICE
          - API_ENTE
          - API_PAGOPA
          - API_PAGAMENTO
          - API_PENDENZE
          - API_RAGIONERIA
          - API_BACKEND_IO
          - API_SECIM
          - API_MYPIVOT
          - API_MAGGIOLI_JPPA
          - API_GOVPAY
          - API_HYPERSIC_APK
          - API_USER
          - GOVPAY
        categoriaEvento:
          type: string
          enum:
          - INTERNO
          - INTERFACCIA
          - UTENTE
        ruolo:
          type: string
          enum:
          - CLIENT
          - SERVER
        tipoEvento:
          maxLength: 255
          minLength: 0
          type: string
        esito:
          type: string
          enum:
          - OK
          - KO
          - FAIL
        dataEvento:
          type: string
          format: date-time
        durataEvento:
          type: integer
          format: int64
        sottotipoEvento:
          maxLength: 255
          minLength: 0
          type: string
        sottotipoEsito:
          maxLength: 255
          minLength: 0
          type: string
        dettaglioEsito:
          type: string
        idDominio:
          pattern: "(^([0-9]){11}$)"
          type: string
        iuv:
          maxLength: 35
          minLength: 0
          type: string
        ccp:
          maxLength: 35
          minLength: 0
          type: string
        idA2A:
          pattern: "(^[a-zA-Z0-9\\-_]{1,35}$)"
          type: string
        idPendenza:
          pattern: "(^[a-zA-Z0-9\\-_]{1,35}$)"
          type: string
        idPagamento:
          maxLength: 35
          minLength: 0
          type: string
        datiPagoPA:
          $ref: '#/components/schemas/datiPagoPA'
        severita:
          maximum: 5
          minimum: 0
          type: integer
          format: int32
        parametriRichiesta:
          type: object
        parametriRisposta:
          type: object
        idTracciato:
          type: integer
          format: int64
        idFr:
          type: integer
          format: int64
        idRiconciliazione:
          type: integer
          format: int64
      description: Evento da salvare.
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    PagedModel:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            objects:
              type: array
              items:
                type: object
        _links:
          $ref: '#/components/schemas/Links'
        page:
          $ref: '#/components/schemas/PageMetadata'
    evento:
      type: object
      properties:
        id:
          type: integer
          format: int64
        componente:
          type: string
          enum:
          - API_BACKOFFICE
          - API_ENTE
          - API_PAGOPA
          - API_PAGAMENTO
          - API_PENDENZE
          - API_RAGIONERIA
          - API_BACKEND_IO
          - API_SECIM
          - API_MYPIVOT
          - API_MAGGIOLI_JPPA
          - API_GOVPAY
          - API_HYPERSIC_APK
          - API_USER
          - GOVPAY
        categoriaEvento:
          type: string
          enum:
          - INTERNO
          - INTERFACCIA
          - UTENTE
        ruolo:
          type: string
          enum:
          - CLIENT
          - SERVER
        tipoEvento:
          maxLength: 255
          minLength: 0
          type: string
        esito:
          type: string
          enum:
          - OK
          - KO
          - FAIL
        dataEvento:
          type: string
          format: date-time
        durataEvento:
          type: integer
          format: int64
        sottotipoEvento:
          maxLength: 255
          minLength: 0
          type: string
        sottotipoEsito:
          maxLength: 255
          minLength: 0
          type: string
        dettaglioEsito:
          type: string
        idDominio:
          pattern: "(^([0-9]){11}$)"
          type: string
        iuv:
          maxLength: 35
          minLength: 0
          type: string
        ccp:
          maxLength: 35
          minLength: 0
          type: string
        idA2A:
          pattern: "(^[a-zA-Z0-9\\-_]{1,35}$)"
          type: string
        idPendenza:
          pattern: "(^[a-zA-Z0-9\\-_]{1,35}$)"
          type: string
        idPagamento:
          maxLength: 35
          minLength: 0
          type: string
        datiPagoPA:
          $ref: '#/components/schemas/datiPagoPA'
        severita:
          maximum: 5
          minimum: 0
          type: integer
          format: int32
        parametriRichiesta:
          type: object
        parametriRisposta:
          type: object
        _links:
          $ref: '#/components/schemas/Links'
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
